### ISSUE TITLE
Tegu Combination

### ISSUE THREAD

**Issue by MasterPa** [generalized-intelligence/GAAS#10]
Add model training ability to GAAS to realize custom object detection ability or other deep learing tasks.

We could use another open source program Tegu to do this.

https://github.com/generalized-intelligence/Tegu

**Comment by cyanine-gi** [comment]
For users:
Check algorithms/image_detection/tegu_detection_demo.py.
It is not a prior task for GAAS team now, for we are working on position fusion and scene retrieving application, which is more critical for GAAS.
And also personally I strongly do not recommend anyone use Nvidia tx2 or Nano (especially Nano) for further develop of autonomous driving, for the performance of these arm CPUs is too poor.To save your time, get started with your laptop with x86 CPU in simulator and deploy with NUC is a better choice.
I'll close this, still anyone who has new requirements of object detection can leave a message here.
