### ISSUE TITLE
对tutorial6，我能用px4的V1.9.2版本的源码进行仿真吗

### ISSUE THREAD

**Issue by Lndulge666** [generalized-intelligence/GAAS#102]
* Tutorial 6
* ROS: Kinetic
* Gazebo: 9
* Ubuntu: 16.04

我能用px4的V1.9.2版本的源码进行仿真吗，因为在输入下面这行指令的时候
cp -r (GAAS_PATH)/simulator/posix-config/* ~/catkin_ws/src/Firmware/posix-configs/SITL/init/ekf2/
发现v1.9.2版本的源码没有后面那个文件夹

**Comment by cyanine-gi** [comment]
We have not checked other versions of px4. Maybe you should search the new path of posix config in 1.9.2.
And please use English in issues so that others can understand.
