### ISSUE TITLE
how to transplant the kcf from the object?

### ISSUE THREAD

**Issue by liangpu597** [generalized-intelligence/GAAS#107]
I have a project, and i want to do ： uav detection and track. 
now i have git clone the project：darknet-ros. and  i can control the uav by keyboardcommand to fly and detection the object in the world. and i want to track.
so, i see this project is cover track programming: kcf .
i want to transplant the kcf model to my project. and i'm fresh man.
i don't know  how to do ?

**Comment by cyanine-gi** [comment]
checkout https://gaas.gitbook.io/guide/software-realization-build-your-own-autonomous-drone/basic-object-tracking
analyze your darknet output bbox, add a data association algorithm and make the output msg just like kcf.
