### ISSUE TITLE
can‘t receive image using rviz

### ISSUE THREAD

**Issue by StancyMiller** [generalized-intelligence/GAAS#119]
I'm using virtual machine ubuntu 16.04.
When I tried the Basic Object Tracking demo(Tutorial 6), I could open the simulation scene in Gazebo and run init_drone.py.
But when I open rviz and chose “Add”->“by topic”->”/gi/simulation/left/image_raw“ to see the drone's view, it didn't work and showed "no image".
So I wonder if the demo could be run on virtual machine.
![2020-08-10 12-01-05屏幕截图](https://user-images.githubusercontent.com/53650786/89751081-42c6da80-db01-11ea-8284-eaa30f3f4b03.png)

**Comment by StancyMiller** [comment]
Ohhhh, it was because of the version of Gazebo. The image can be shown after I update Gazebo to 7.16. The issue could be closed.

**Comment by cyanine-gi** [comment]
Maybe you need some patience when using gazebo :)
