### ISSUE TITLE
[BUG]Drone fly randomly

### ISSUE THREAD

**Issue by Rindelwald** [generalized-intelligence/GAAS#122]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version of GAAS
- [ ] I checked the Gitbook documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I Googled/Binged the error messages generated by Ubuntu, Gazebo, and PX4
- [ ] I have posted questions regarding Ubuntu, Gazebo, and PX4 in corresponding forums.

# Issue Template

## Context
Use GAAS v0.7 Release Mirror - x64.

## Expected Behavior
The drone is flying correctly.

## Current Behavior
There is nothing wrong with running according to the tutorial, but when I modify the flight altitude or flight path in the script, the drone starts to fly randomly.

## Failure Logs

Copy console log and paste it here.

[Wrn] [GuiIface.cc:199] g/gui-plugin is really loading a SystemPlugin. To load a GUI plugin please use --gui-client-plugin 
[ INFO] [1605234219.246981344]: Plugin setpoint_raw initialized
[ INFO] [1605234219.247168699]: Plugin setpoint_velocity loaded
[ INFO] [1605234219.254120790]: Plugin setpoint_velocity initialized
[ INFO] [1605234219.254366440]: Plugin sys_status loaded
[ INFO] [1605234219.268671058]: Plugin sys_status initialized
[ INFO] [1605234219.268808949]: Plugin sys_time loaded
[ INFO] [1605234219.271963331]: TM: Timesync mode: MAVLINK
[ INFO] [1605234219.273079814]: Plugin sys_time initialized
[ INFO] [1605234219.273206665]: Plugin trajectory loaded
[ INFO] [1605234219.276646069]: Plugin trajectory initialized
[ INFO] [1605234219.276781764]: Plugin vfr_hud loaded
[ INFO] [1605234219.277506861]: Plugin vfr_hud initialized
[ INFO] [1605234219.277572684]: Plugin vibration blacklisted
[ INFO] [1605234219.277661519]: Plugin vision_pose_estimate loaded
[ INFO] [1605234219.282129560]: Plugin vision_pose_estimate initialized
[ INFO] [1605234219.282588973]: Plugin vision_speed_estimate loaded
[ INFO] [1605234219.285729429]: Plugin vision_speed_estimate initialized
[ INFO] [1605234219.285866661]: Plugin waypoint loaded
[ INFO] [1605234219.289235241]: Plugin waypoint initialized
[ INFO] [1605234219.289323151]: Plugin wheel_odometry blacklisted
[ INFO] [1605234219.289474239]: Plugin wind_estimation loaded
[ INFO] [1605234219.291564978]: Plugin wind_estimation initialized
[ INFO] [1605234219.291681679]: Autostarting mavlink via USB on PX4
[ INFO] [1605234219.291825162]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1605234219.291866640]: Built-in MAVLink package version: 2019.10.10
[ INFO] [1605234219.291912920]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1605234219.291951903]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ INFO] [1605234219.353769507]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1605234219.356333243]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.114.146
[ INFO] [1605234219.390522269]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1605234219.391968114]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.114.146
[INFO] [1605234219.586250, 0.000000]: Loading model XML from file /root/Firmware/Tools/sitl_gazebo/models/iris_stereo_gray_no_gps/iris_stereo_gray_no_gps.sdf
[INFO] [1605234219.596904, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[Wrn] [GuiIface.cc:120] QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
[Wrn] [GuiIface.cc:120] Qt: Session management error: None of the authentication protocols specified are supported
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/cmake"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/external"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/include"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/models"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/msgs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/scripts"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/src"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/worlds"
[ INFO] [1605234221.532867930, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1605234221.586211800, 0.068000000]: Physics dynamic reconfigure ready.
[INFO] [1605234221.712223, 0.184000]: Calling service /gazebo/spawn_sdf_model
Warning [parser.cc:950] XML Element[child], child of element[sensor] not defined in SDF. Ignoring[child]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
Warning [parser.cc:950] XML Element[parent], child of element[sensor] not defined in SDF. Ignoring[parent]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
[Wrn] [msgs.cc:1852] Conversion of sensor type[multicamera] not supported.
[INFO] [1605234221.981458, 0.380000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1605234222.214934091, 0.380000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1605234222.215359586, 0.380000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1605234222.219882024, 0.380000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1605234222.220076912, 0.380000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[0] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[1] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[2] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[3] no joint control will be performed for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::propeller_joint] not found for channel[4] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_left_joint] not found for channel[5] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_right_joint] not found for channel[6] no joint control for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[7] no joint control will be performed for this channel.
[Msg] Using MAVLink protocol v2.0
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motors, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/0, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/1, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/2, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/imu, deleting message. This warning is printed only once.
[Wrn] [msgs.cc:1852] Conversion of sensor type[multicamera] not supported.
[Wrn] [msgs.cc:1852] Conversion of sensor type[multicamera] not supported.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/3, deleting message. This warning is printed only once.
[vehicle_spawn_ubuntu_27657_2745783485089896165-5] process has finished cleanly
log file: /root/.ros/log/3d07e094-2557-11eb-b2c0-000c2937367d/vehicle_spawn_ubuntu_27657_2745783485089896165-5*.log
INFO  [simulator] Got initial simulation data, running sim..
INFO  [pwm_out_sim] MODE_16PWM
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
INFO  pxh> [logger] logger started (mode=all)
INFO  [logger] removing log directory rootfs/fs/microsd/log/2020-11-06 to get more space (left=18540 MiB)
INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2020-11-13/02_23_43.ulg
INFO  [mavlink] partner IP: 127.0.0.1
[ INFO] [1605234223.630729943, 1.588000000]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1605234223.716337857, 1.674000000]: IMU: High resolution IMU detected!
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
[ INFO] [1605234224.554288123, 2.508000000]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1605234224.556135428, 2.510000000]: IMU: High resolution IMU detected!
[ INFO] [1605234224.641411363, 2.596000000]: IMU: Attitude quaternion IMU detected!
[ INFO] [1605234225.567848155, 3.510000000]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1605234225.567997504, 3.510000000]: VER: 1.1: Flight software:     010800ff (96443b3cf3e3adae)
[ INFO] [1605234225.568077363, 3.510000000]: VER: 1.1: Middleware software: 010800ff (96443b3cf3e3adae)
[ INFO] [1605234225.568326012, 3.510000000]: VER: 1.1: OS software:         041200ff (0000000000000000)
[ INFO] [1605234225.568362229, 3.510000000]: VER: 1.1: Board hardware:      00000001
[ INFO] [1605234225.568389244, 3.510000000]: VER: 1.1: VID/PID:             0000:0000
[ INFO] [1605234225.568402566, 3.510000000]: VER: 1.1: UID:                 0000000100000002
[Err] [ModelDatabase.cc:390] Unable to parse model.config for model[http://gazebosim.org/models/bin_4_dropping_task]
[ INFO] [1605234234.578604754, 12.508000000]: HP: requesting home position
[ INFO] [1605234239.598240953, 17.508000000]: WP: mission received
[ INFO] [1605234244.751545961, 22.508000000]: HP: requesting home position
[ INFO] [1605234255.254127049, 32.508000000]: HP: requesting home position
[ INFO] [1605234265.493696208, 42.508000000]: HP: requesting home position
[ERROR] [1605234275.760815471, 52.300000000]: TM : Time jump detected. Resetting time synchroniser.
[ INFO] [1605234275.977457859, 52.508000000]: HP: requesting home position
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ INFO] [1605234286.549727789, 62.508000000]: HP: requesting home position
[ INFO] [1605234296.706374027, 72.508000000]: HP: requesting home position
[ INFO] [1605234306.771931743, 82.508000000]: HP: requesting home position
[ INFO] [1605234316.833503185, 92.508000000]: HP: requesting home position
[ INFO] [1605234326.904022316, 102.508000000]: HP: requesting home position
[ INFO] [1605234336.932057548, 112.508000000]: HP: requesting home position
[ INFO] [1605234346.969945950, 122.508000000]: HP: requesting home position
[ERROR] [1605234351.807194752, 127.302000000]: TM : Time jump detected. Resetting time synchroniser.
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ INFO] [1605234357.056590887, 132.508000000]: HP: requesting home position
[ INFO] [1605234367.095278685, 142.508000000]: HP: requesting home position
[ INFO] [1605234377.281085496, 152.508000000]: HP: requesting home position
[ INFO] [1605234387.511056173, 162.508000000]: HP: requesting home position
[ INFO] [1605234398.003614055, 172.508000000]: HP: requesting home position
[ INFO] [1605234408.191269804, 182.508000000]: HP: requesting home position
[ INFO] [1605234418.371790901, 192.508000000]: HP: requesting home position
[ INFO] [1605234428.505742907, 202.508000000]: HP: requesting home position
[ INFO] [1605234438.707173195, 212.508000000]: HP: requesting home position
[ INFO] [1605234448.832267496, 222.508000000]: HP: requesting home position
[ INFO] [1605234458.923663540, 232.508000000]: HP: requesting home position
[ INFO] [1605234468.962346431, 242.508000000]: HP: requesting home position
[ INFO] [1605234479.380562204, 252.508000000]: HP: requesting home position
[ INFO] [1605234489.534405348, 262.508000000]: HP: requesting home position
[ INFO] [1605234499.569031161, 272.508000000]: HP: requesting home position
[ INFO] [1605234509.734599212, 282.508000000]: HP: requesting home position
[ INFO] [1605234519.926532385, 292.508000000]: HP: requesting home position
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ERROR] [1605234527.244539309, 299.402000000]: TM : Time jump detected. Resetting time synchroniser.
[ INFO] [1605234530.504496436, 302.508000000]: HP: requesting home position
[ INFO] [1605234540.960372458, 312.508000000]: HP: requesting home position
[ INFO] [1605234551.211840218, 322.508000000]: HP: requesting home position
[ INFO] [1605234561.711228073, 332.508000000]: HP: requesting home position
[ INFO] [1605234572.110271541, 342.508000000]: HP: requesting home position
[ INFO] [1605234582.354260750, 352.508000000]: HP: requesting home position
[ INFO] [1605234592.596762101, 362.508000000]: HP: requesting home position
[ INFO] [1605234602.885799406, 372.508000000]: HP: requesting home position
[ INFO] [1605234613.268175352, 382.508000000]: HP: requesting home position
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ INFO] [1605234623.441150764, 392.508000000]: HP: requesting home position
[ INFO] [1605234633.823084398, 402.508000000]: HP: requesting home position
[ERROR] [1605234640.095935167, 408.100000000]: TM : Time jump detected. Resetting time synchroniser.
INFO  [mavlink] partner IP: 127.0.0.1
[ WARN] [1605234641.250626034, 409.124000000]: CMD: Unexpected command 520, result 0
[ INFO] [1605234644.897291608, 412.508000000]: HP: requesting home position
[ INFO] [1605234656.360385053, 422.508000000]: HP: requesting home position
[ WARN] [1605234660.016096698, 425.818000000]: PR: Param EKF2_AID_MASK (113/527): <value><i4>8</i4></value> different index: 126/542
INFO  [ecl/EKF] EKF commencing external vision position fusion
[ WARN] [1605234665.322767395, 430.726000000]: CMD: Unexpected command 246, result 0
[ INFO] [1605234667.257559212, 432.508000000]: HP: requesting home position
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ INFO] [1605234678.285608360, 442.508000000]: HP: requesting home position
WARN  [commander_tests] Failsafe enabled: no RC
[ WARN] [1605234686.552787620, 450.088000000]: CMD: Unexpected command 176, result 1
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/gazebo/command/motor_speed, deleting message. This warning is printed only once.
[ INFO] [1605234686.619250065, 450.130000000]: WP: reached #0
[ INFO] [1605234686.639326668, 450.148000000]: WP: reached #0
[ INFO] [1605234686.775552147, 450.274000000]: WP: reached #0
[ INFO] [1605234686.902169775, 450.388000000]: WP: reached #0
INFO  [commander] Takeoff detected
[ INFO] [1605234687.050346041, 450.516000000]: WP: reached #0
[ INFO] [1605234687.186081084, 450.616000000]: WP: reached #0
[ INFO] [1605234687.319607558, 450.730000000]: WP: reached #0
[ INFO] [1605234687.466776929, 450.856000000]: WP: reached #0
[ INFO] [1605234687.600547931, 450.970000000]: WP: reached #0
[ INFO] [1605234687.723964574, 451.082000000]: WP: reached #0
[ INFO] [1605234687.866465497, 451.190000000]: WP: reached #0
[ INFO] [1605234689.406128499, 452.508000000]: HP: requesting home position
[ INFO] [1605234700.690501847, 462.508000000]: HP: requesting home position
[ INFO] [1605234711.662041721, 472.508000000]: HP: requesting home position
[ INFO] [1605234722.618143371, 482.508000000]: HP: requesting home position
[ INFO] [1605234733.790904926, 492.508000000]: HP: requesting home position
[ INFO] [1605234744.702598197, 502.508000000]: HP: requesting home position
[ INFO] [1605234755.129989033, 512.508000000]: HP: requesting home position
[ INFO] [1605234765.513815331, 522.508000000]: HP: requesting home position
[ INFO] [1605234775.924461876, 532.508000000]: HP: requesting home position
[ERROR] [1605234778.980849113, 535.400000000]: TM : Time jump detected. Resetting time synchroniser.
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ INFO] [1605234786.345603771, 542.508000000]: HP: requesting home position
[ INFO] [1605234796.700351726, 552.508000000]: HP: requesting home position
[ INFO] [1605234807.187908091, 562.508000000]: HP: requesting home position
[ INFO] [1605234817.531942932, 572.508000000]: HP: requesting home position
[ INFO] [1605234828.024244806, 582.508000000]: HP: requesting home position
[ INFO] [1605234839.120616672, 592.508000000]: HP: requesting home position
[ INFO] [1605234850.231911898, 602.508000000]: HP: requesting home position
[ERROR] [1605234855.410442115, 606.904000000]: TM : Time jump detected. Resetting time synchroniser.
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ INFO] [1605234862.375326202, 612.510000000]: HP: requesting home position
[ INFO] [1605234873.696812301, 622.508000000]: HP: requesting home position
[ INFO] [1605234884.578538249, 632.508000000]: HP: requesting home position
[ INFO] [1605234895.881521322, 642.508000000]: HP: requesting home position
[ INFO] [1605234907.924032212, 652.508000000]: HP: requesting home position
[ERROR] [1605234913.769520993, 657.502000000]: TM : Time jump detected. Resetting time synchroniser.
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ INFO] [1605234919.744336067, 662.508000000]: HP: requesting home position
[ INFO] [1605234931.324344820, 672.508000000]: HP: requesting home position
[ INFO] [1605234942.717916632, 682.508000000]: HP: requesting home position
[ INFO] [1605234953.793146398, 692.510000000]: HP: requesting home position
[ INFO] [1605234964.904520357, 702.508000000]: HP: requesting home position
[ERROR] [1605234971.249737026, 708.100000000]: TM : Time jump detected. Resetting time synchroniser.
[ INFO] [1605234976.160811706, 712.510000000]: HP: requesting home position
[ INFO] [1605234987.378687709, 722.508000000]: HP: requesting home position
[ INFO] [1605234999.361816716, 732.510000000]: HP: requesting home position
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ INFO] [1605235011.445991405, 742.508000000]: HP: requesting home position
[ INFO] [1605235022.251869580, 752.508000000]: HP: requesting home position
[ERROR] [1605235028.814865088, 758.702000000]: TM : Time jump detected. Resetting time synchroniser.
[ INFO] [1605235032.841998349, 762.508000000]: HP: requesting home position
[ INFO] [1605235043.421839596, 772.508000000]: HP: requesting home position
[mavros-6] killing on exit
[gazebo_gui-4] killing on exit
[sitl-2] killing on exit
[gazebo-3] killing on exit

Exiting...
pxh> Shutting down
Restoring terminal
[gazebo_gui-4] escalating to SIGTERM
[gazebo-3] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
[slam.log](https://github.com/generalized-intelligence/GAAS/files/5535176/slam.log)

**Comment by cyanine-gi** [comment]
It is not a bug. Since you are using iris model without gps,  you should always keep the camera view clear and there are some valid keypoints in sight. It is not that stable when using vSLAM in too simple env.
We suggest you add some obstacles in your view and do not plan paths that are too high from ground.

If you just wanna control the drone with a path you selected, just replace iris_without_gps with simple iris model and using gps for your localization.

If you wanna simulate the gps-denied env and you need a robust implementation, maybe you should checkout GAAS_contrib, a lidar-based localization algorithm is included.
