### ISSUE TITLE
[BUG] CRITICAL NAVIGATION FAILURE - CHECK SENSOR CALIBRATION

### ISSUE THREAD

**Issue by Rindelwald** [generalized-intelligence/GAAS#123]
# Issue Template

## Context
use GAAS v0.7 Release Mirror - x64 in  Ubuntu 18.04.

## Expected Behavior
vehicle fly as expected.

## Current Behavior
When the error occurs, the vehicle flying randomly.

## Failure Logs

.. logging to /root/.ros/log/09e6cfcc-27b4-11eb-a3f6-000c2937367d/roslaunch-ubuntu-32718.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/loader.py:412: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(text)
started roslaunch server http://ubuntu:34725/

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/landing_target/camera/fov_x: 2.0071286398
 * /mavros/landing_target/camera/fov_y: 2.0071286398
 * /mavros/landing_target/image/height: 480
 * /mavros/landing_target/image/width: 640
 * /mavros/landing_target/land_target_type: VISION_FIDUCIAL
 * /mavros/landing_target/listen_lt: False
 * /mavros/landing_target/mav_frame: LOCAL_NED
 * /mavros/landing_target/target_size/x: 0.3
 * /mavros/landing_target/target_size/y: 0.3
 * /mavros/landing_target/tf/child_frame_id: camera_center
 * /mavros/landing_target/tf/frame_id: landing_target
 * /mavros/landing_target/tf/listen: False
 * /mavros/landing_target/tf/rate_limit: 10.0
 * /mavros/landing_target/tf/send: True
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/fcu/odom_child_id_des: base_link
 * /mavros/odometry/fcu/odom_parent_id_des: map
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: odom
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: odom
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: odom
 * /mavros/wheel_odometry/tf/send: False
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mavros (mavros/mavros_node)
    sitl (px4/px4)
    vehicle_spawn_ubuntu_32718_1045543776475254924 (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [32728]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 09e6cfcc-27b4-11eb-a3f6-000c2937367d
process[rosout-1]: started with pid [32739]
started core service [/rosout]
process[sitl-2]: started with pid [32747]
node name: sitl
data path: /root/Firmware
commands file: /root/Firmware/posix-configs/SITL/init/ekf2/iris_stereo_gray_no_gps

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

process[gazebo-3]: started with pid [32752]
process[gazebo_gui-4]: started with pid [32757]
process[vehicle_spawn_ubuntu_32718_1045543776475254924-5]: started with pid [32760]
process[mavros-6]: started with pid [32763]
INFO  [dataman] Unknown restart, data manager file 'rootfs/fs/microsd/dataman' size is 11405132 bytes
+ EKF2_AID_MASK: curr: 8 -> new: 1
INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..
[ INFO] [1605493978.828062115]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1605493978.829224887]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1605493978.829326908]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1605493978.829432041]: GCS bridge disabled
[ INFO] [1605493978.836278936]: Plugin 3dr_radio loaded
[ INFO] [1605493978.837399461]: Plugin 3dr_radio initialized
[ INFO] [1605493978.837538971]: Plugin actuator_control loaded
[ INFO] [1605493978.839142733]: Plugin actuator_control initialized
[ INFO] [1605493978.841717660]: Plugin adsb loaded
[ INFO] [1605493978.844244208]: Plugin adsb initialized
[ INFO] [1605493978.844354846]: Plugin altitude loaded
[ INFO] [1605493978.845037398]: Plugin altitude initialized
[ INFO] [1605493978.845142158]: Plugin cam_imu_sync loaded
[ INFO] [1605493978.845547512]: Plugin cam_imu_sync initialized
[ INFO] [1605493978.845650652]: Plugin command loaded
[ INFO] [1605493978.848921543]: Plugin command initialized
[ INFO] [1605493978.849038644]: Plugin companion_process_status loaded
[ INFO] [1605493978.850406990]: Plugin companion_process_status initialized
[ INFO] [1605493978.850546556]: Plugin debug_value loaded
[ INFO] [1605493978.853232794]: Plugin debug_value initialized
[ INFO] [1605493978.853304933]: Plugin distance_sensor blacklisted
[ INFO] [1605493978.853401025]: Plugin fake_gps loaded
[ INFO] [1605493978.861999894]: Plugin fake_gps initialized
[ INFO] [1605493978.862191346]: Plugin ftp loaded
[ INFO] [1605493978.866016738]: Plugin ftp initialized
[ INFO] [1605493978.866158200]: Plugin global_position loaded
[ INFO] [1605493978.895770369]: Plugin global_position initialized
[ INFO] [1605493978.895883190]: Plugin gps_rtk loaded
[ INFO] [1605493978.897410834]: Plugin gps_rtk initialized
[ INFO] [1605493978.897537673]: Plugin hil loaded
[ INFO] [1605493978.904596870]: Plugin hil initialized
[ INFO] [1605493978.904722145]: Plugin home_position loaded
[ INFO] [1605493978.906915105]: Plugin home_position initialized
[ INFO] [1605493978.907030139]: Plugin imu loaded
[ INFO] [1605493978.914037100]: Plugin imu initialized
[ INFO] [1605493978.914251731]: Plugin landing_target loaded
[ INFO] [1605493978.947145515]: Plugin landing_target initialized
[ INFO] [1605493978.947262497]: Plugin local_position loaded
[ INFO] [1605493978.953010412]: Plugin local_position initialized
[ INFO] [1605493978.953187995]: Plugin log_transfer loaded
[ INFO] [1605493978.955624348]: Plugin log_transfer initialized
[ INFO] [1605493978.955755500]: Plugin manual_control loaded
[ INFO] [1605493978.957629812]: Plugin manual_control initialized
[ INFO] [1605493978.957747193]: Plugin mocap_pose_estimate loaded
[ INFO] [1605493978.959856113]: Plugin mocap_pose_estimate initialized
[ INFO] [1605493978.959980094]: Plugin mount_control loaded
[ INFO] [1605493978.969849269]: Plugin mount_control initialized
[ INFO] [1605493978.969981984]: Plugin obstacle_distance loaded
[ INFO] [1605493978.971212296]: Plugin obstacle_distance initialized
[ INFO] [1605493978.971309403]: Plugin odom loaded
[ INFO] [1605493978.980492791]: Plugin odom initialized
[ INFO] [1605493978.980632796]: Plugin onboard_computer_status loaded
[ INFO] [1605493978.982963273]: Plugin onboard_computer_status initialized
[ INFO] [1605493978.983131249]: Plugin param loaded
Gazebo multi-robot simulator, version 9.0.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Wrn] [GuiIface.cc:199] g/gui-plugin is really loading a SystemPlugin. [ INFO] [1605493978.985853872]: Plugin param initialized
[ INFO] [1605493978.985975375]: Plugin px4flow loaded
To load a GUI plugin please use --gui-client-plugin 
Gazebo multi-robot simulator, version 9.0.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1605493978.991523097]: Plugin px4flow initialized
[ INFO] [1605493978.991583675]: Plugin rangefinder blacklisted
[ INFO] [1605493978.991670839]: Plugin rc_io loaded
[ INFO] [1605493979.003903928]: Plugin rc_io initialized
[ INFO] [1605493979.004162761]: Plugin safety_area blacklisted
[ INFO] [1605493979.004369013]: Plugin setpoint_accel loaded
[ INFO] [1605493979.007396786]: Plugin setpoint_accel initialized
[ INFO] [1605493979.007536078]: Plugin setpoint_attitude loaded
[ INFO] [1605493979.012677869]: Plugin setpoint_attitude initialized
[ INFO] [1605493979.012812175]: Plugin setpoint_position loaded
[ INFO] [1605493979.036197849]: Plugin setpoint_position initialized
[ INFO] [1605493979.036368133]: Plugin setpoint_raw loaded
[ INFO] [1605493979.043891122]: Plugin setpoint_raw initialized
[ INFO] [1605493979.044056619]: Plugin setpoint_velocity loaded
[ INFO] [1605493979.050677773]: Plugin setpoint_velocity initialized
[ INFO] [1605493979.050872516]: Plugin sys_status loaded
[ INFO] [1605493979.059042231]: Plugin sys_status initialized
[ INFO] [1605493979.059238222]: Plugin sys_time loaded
[ INFO] [1605493979.063465455]: TM: Timesync mode: MAVLINK
[ INFO] [1605493979.064879334]: Plugin sys_time initialized
[ INFO] [1605493979.065027280]: Plugin trajectory loaded
[ INFO] [1605493979.071087025]: Plugin trajectory initialized
[ INFO] [1605493979.071288874]: Plugin vfr_hud loaded
[ INFO] [1605493979.071963553]: Plugin vfr_hud initialized
[ INFO] [1605493979.072053567]: Plugin vibration blacklisted
[ INFO] [1605493979.072177428]: Plugin vision_pose_estimate loaded
[ INFO] [1605493979.079764759]: Plugin vision_pose_estimate initialized
[ INFO] [1605493979.079922781]: Plugin vision_speed_estimate loaded
[ INFO] [1605493979.083919096]: Plugin vision_speed_estimate initialized
[ INFO] [1605493979.084102593]: Plugin waypoint loaded
[ INFO] [1605493979.087930410]: Plugin waypoint initialized
[ INFO] [1605493979.088000046]: Plugin wheel_odometry blacklisted
[ INFO] [1605493979.088156260]: Plugin wind_estimation loaded
[ INFO] [1605493979.088890294]: Plugin wind_estimation initialized
[ INFO] [1605493979.088976810]: Autostarting mavlink via USB on PX4
[ INFO] [1605493979.089158593]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1605493979.089219502]: Built-in MAVLink package version: 2019.10.10
[ INFO] [1605493979.089277969]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1605493979.089326272]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ INFO] [1605493979.102278317]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1605493979.104738983]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.114.148
[ INFO] [1605493979.174384305]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1605493979.178002708]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.114.148
[INFO] [1605493979.419650, 0.000000]: Loading model XML from file /root/Firmware/Tools/sitl_gazebo/models/iris_stereo_gray_no_gps/iris_stereo_gray_no_gps.sdf
[INFO] [1605493979.427926, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[Wrn] [GuiIface.cc:120] QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
[Wrn] [GuiIface.cc:120] Qt: Session management error: None of the authentication protocols specified are supported
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/cmake"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/external"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/include"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/models"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/msgs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/scripts"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/src"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/root/Firmware/Tools/sitl_gazebo/worlds"
[ INFO] [1605493981.212947737, 1502.730000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1605493981.239421, 1502.742000]: Calling service /gazebo/spawn_sdf_model
[ INFO] [1605493981.249094709, 1502.750000000]: Physics dynamic reconfigure ready.
[Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
Warning [parser.cc:950] XML Element[child], child of element[sensor] not defined in SDF. Ignoring[child]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
Warning [parser.cc:950] XML Element[parent], child of element[sensor] not defined in SDF. Ignoring[parent]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
[Wrn] [msgs.cc:1852] Conversion of sensor type[multicamera] not supported.
[INFO] [1605493981.457613, 1502.878000]: Spawn status: SpawnModel: Successfully spawned entity
[Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
[vehicle_spawn_ubuntu_32718_1045543776475254924-5] process has finished cleanly
log file: /root/.ros/log/09e6cfcc-27b4-11eb-a3f6-000c2937367d/vehicle_spawn_ubuntu_32718_1045543776475254924-5*.log
[ INFO] [1605493981.657686711, 1502.878000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1605493981.658189474, 1502.878000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1605493981.662416196, 1502.878000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1605493981.670994976, 1502.878000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[0] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[1] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[2] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[3] no joint control will be performed for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::propeller_joint] not found for channel[4] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_left_joint] not found for channel[5] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_right_joint] not found for channel[6] no joint control for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[7] no joint control will be performed for this channel.
[Msg] Using MAVLink protocol v2.0
[Wrn] [msgs.cc:1852] Conversion of sensor type[multicamera] not supported.
[Wrn] [msgs.cc:1852] Conversion of sensor type[multicamera] not supported.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motors, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/0, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/1, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/2, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/3, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/imu, deleting message. This warning is printed only once.
INFO  [simulator] Got initial simulation data, running sim..
INFO  [pwm_out_sim] MODE_16PWM
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2020-11-16/02_33_03.ulg
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
pxh> INFO  [mavlink] partner IP: 127.0.0.1
[ INFO] [1605493983.061046862, 1504.018000000]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1605493983.224624336, 1504.172000000]: IMU: High resolution IMU detected!
INFO  [mavlink] partner IP: 127.0.0.1
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
[ INFO] [1605493983.844961081, 1504.790000000]: IMU: Attitude quaternion IMU detected!
[ INFO] [1605493984.011001985, 1504.954000000]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1605493984.011766339, 1504.954000000]: IMU: Attitude quaternion IMU detected!
[ INFO] [1605493984.029368627, 1504.972000000]: IMU: High resolution IMU detected!
[ WARN] [1605493984.153803589, 1505.098000000]: CMD: Unexpected command 520, result 0
[ INFO] [1605493985.087056464, 1505.956000000]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1605493985.087148029, 1505.956000000]: VER: 1.1: Flight software:     010800ff (96443b3cf3e3adae)
[ INFO] [1605493985.087181683, 1505.956000000]: VER: 1.1: Middleware software: 010800ff (96443b3cf3e3adae)
[ INFO] [1605493985.087195235, 1505.956000000]: VER: 1.1: OS software:         041200ff (0000000000000000)
[ INFO] [1605493985.087232213, 1505.956000000]: VER: 1.1: Board hardware:      00000001
[ INFO] [1605493985.087249627, 1505.956000000]: VER: 1.1: VID/PID:             0000:0000
[ INFO] [1605493985.087286879, 1505.956000000]: VER: 1.1: UID:                 0000000100000002
[Err] [ModelDatabase.cc:390] Unable to parse model.config for model[http://gazebosim.org/models/bin_4_dropping_task]
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/pose/local/info, deleting message. This warning is printed only once.
[ INFO] [1605493994.973772997, 1514.954000000]: HP: requesting home position
[ INFO] [1605494001.188529934, 1519.954000000]: WP: mission received
INFO  [ecl/EKF] EKF commencing external vision position fusion
[ INFO] [1605494007.325008270, 1524.956000000]: HP: requesting home position
[ WARN] [1605494008.532523760, 1525.960000000]: CMD: Unexpected command 246, result 0
WARN  [commander_tests] Failsafe enabled: no RC
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/gazebo/command/motor_speed, deleting message. This warning is printed only once.
[ INFO] [1605494019.116748649, 1533.316000000]: WP: reached #0
[ INFO] [1605494019.133370643, 1533.326000000]: WP: reached #0
[ INFO] [1605494019.300236581, 1533.420000000]: WP: reached #0
[ INFO] [1605494019.479836234, 1533.528000000]: WP: reached #0
INFO  [commander] Takeoff detected
[ INFO] [1605494019.665926752, 1533.614000000]: WP: reached #0
[ INFO] [1605494019.836648417, 1533.724000000]: WP: reached #0
[ INFO] [1605494020.001347697, 1533.822000000]: WP: reached #0
[ INFO] [1605494020.142464193, 1533.932000000]: WP: reached #0
[ INFO] [1605494020.281534471, 1534.020000000]: WP: reached #0
[ INFO] [1605494020.440035084, 1534.114000000]: WP: reached #0
[ INFO] [1605494020.609569289, 1534.226000000]: WP: reached #0
[ INFO] [1605494021.722752462, 1534.954000000]: HP: requesting home position
[ INFO] [1605494038.590043506, 1544.956000000]: HP: requesting home position
ERROR [commander] CRITICAL NAVIGATION FAILURE - CHECK SENSOR CALIBRATION
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ERROR] [1605494055.541724502, 1554.592000000]: TM : Time jump detected. Resetting time synchroniser.
[ INFO] [1605494056.357934664, 1554.954000000]: HP: requesting home position
[ INFO] [1605494074.038377627, 1564.954000000]: HP: requesting home position
[ INFO] [1605494093.154881527, 1574.954000000]: HP: requesting home position
[ INFO] [1605494109.793545238, 1584.954000000]: HP: requesting home position
[mavros-6] killing on exit
[gazebo_gui-4] killing on exit
[gazebo-3] killing on exit
[sitl-2] killing on exit

Exiting...
pxh> Shutting down
Restoring terminal
[gazebo-3] escalating to SIGTERM
[gazebo_gui-4] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by cyanine-gi** [comment]
I've seen this phenomenon  when the vehicle hit something and imu has a large value of acc.
Maybe that is the reason. If you have any clue, reopen this issue please.
