### ISSUE TITLE
Use GAAS with ROS Melodic

### ISSUE THREAD

**Issue by Cristian-wp** [generalized-intelligence/GAAS#126]
- [x ] I am running the latest version of GAAS
- [x ] I checked the Gitbook documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I Googled/Binged the error messages generated by Ubuntu, Gazebo, and PX4
- [x ] I have posted questions regarding Ubuntu, Gazebo, and PX4 in corresponding forums.

* Tutorial No.:1
* Mavros: 1.5.0
* ROS: Melodic
* Gazebo: 9
* Ubuntu: 18.04LTS
* System Platform: x64
----------------------------------------------------------------------------------------------------------------------------------------------

I would like to run the tutorials on ROS Melodic, but I can not solve all the problem about compatibility.
Is possibile to use GAAS on ROS Melodic? If is possible, can someone provide me the package versions used?

Thanks in advance :)

**Comment by cyanine-gi** [comment]
Yes it is! Just change your ros-kinetic-* to ros-melodic-*.
Remember you should still use px4 1.8.0.
