### ISSUE TITLE
SET_POSITION_TARGET_LOCAL_NED coordinate frame 9 unsupported In offboard control

### ISSUE THREAD

**Issue by droidlyx86** [generalized-intelligence/GAAS#129]
In tutorial1(offboard control), px4_mavros_run.py set the coordinate frame of the function SET_POSITION_TARGET_LOCAL_NED to 9 at line 111, resulting in the mavlink warning saying that SET_POSITION_TARGET_LOCAL_NED coordinate frame 9 unsupported, which makes the program unable to set the target location of the drone. So the drone can't take off.

Coordinate frame 9 responds to MAV_FRAME_BODY_OFFSET_NED, however, according to [ROS document](http://wiki.ros.org/mavros/Enumerations), Currently, in PX4 firmware, only MAV_FRAME_LOCAL_NED(coordinate frame 1) is used, which may be the main reason of the problem.

Did the code used to work? it seems to be deprecated now.

**Comment by cyanine-gi** [comment]
Please check your px4 version. We only support px4  1.8.0 officially now.
