### ISSUE TITLE
Didn't find any ros topic about camera data

### ISSUE THREAD

**Issue by ElderWanng** [generalized-intelligence/GAAS#13]
In your tutorial, after running `rostopic list`, there are 2 topics called `/gi/simulation/XX/image_raw`.
But, I follow your tutorial on gitbook and build from source, when I get into the part2, I can't find anything about the camera and I don't know how to use the slam and SfM simulation.
Then I use the docker way for making sure that I didn't miss any tiny. But, still, when I tap in 'rostopic list', `/gi` doesn't show up.

Did I forget building the "gi package" or something related? 

PS: when the next video will be released? XD

THX!
------------------------------------------------------------------------------------------
跟着gitbook的教程走，part1 还好说，part2的时候卡住了，毫无头绪，斗胆来issue提问下。找不到相机数据那个topic，是不是得自己设置相机。还有如何安装，调用slam模块？

**Comment by Doodleshr** [comment]
1. For tutorial 1, we will be using GPS as the prefered position estimation method, so no camera and SLAM will be needed. 
2. Part 2 is not finished yet (sorry for the delay), so you will run to some trouble while following it. You can join our Gitter or Wechat group (as shown in the front page) for more information and help.
3. For topics related to gi/simulation/camera, they are currently not added and they will become available after finishing Part 2. Part 2 should have been ready this week but I was trapped with other works, and I will make it available hopefully during the weekend.
