### ISSUE TITLE
Trouble positioning drone camera to detect QR Code for landing

### ISSUE THREAD

**Issue by DerekLynch** [generalized-intelligence/GAAS#130]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version of GAAS
- [x ] I checked the Gitbook documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I Googled/Binged the error messages generated by Ubuntu, Gazebo, and PX4
- [x ] I have posted questions regarding Ubuntu, Gazebo, and PX4 in corresponding forums.

# Issue Template

## Context
Please provide any relevant information about your setup.
* Tutorial No.:[Tutorial 5]
* Mavros: [0.18.4]
* ROS: [Melodic]
* Gazebo: [9]
* Ubuntu: [18.04]
* System Platform: [x64]

## Expected Behavior

In tutorial E05, I am able to complete the drone takeoff and I am also able to send commands via Commander (as well as manually changing x/y/z/r/p/y in Gazebo). Expecting the drone to eventually recognize the QR code and land safely.

## Current Behavior

Because of the angle of the camera (parallel to the ground) I'm having a hard time choosing (x,y,z) coordinates that allow a good view of the QR code. I have tried the recommended (8,0,0) in the tutorial with no luck. It may seem like a trivial problem but has been a major hang-up.

## Screenshots

N/A

## Failure Logs

N/A

**Comment by cyanine-gi** [comment]
Maybe you should check your frequency of simulation or try other position to recognize the qr code.  Changing the pose of camera on the drone may also help since solve PNP give out the position in QR code coordinate.
