### ISSUE TITLE
 Failsafe enabled: no RC and no offboard INFO  [commander] Failsafe mode activated

### ISSUE THREAD

**Issue by laylow13** [generalized-intelligence/GAAS#131]
Everytime when I run the px4_mavros_run.py in the PX4 SITL, Iwill  see the following outputs
`python px4_mavros_run.py
Px4 Controller Initialized!
Vehicle Took Off Failed!
`
In the QGC,Ican see the following :
` Failsafe enabled: no RC and no offboard
 INFO  [commander] Failsafe mode activated`

**Comment by cyanine-gi** [comment]
Check the output rate of your mavros_controller. It should be always more than 2Hz to ensure the vehicle stays in OFFBOARD_MODE.
