### ISSUE TITLE
"move/take off" behavior is not working rightly

### ISSUE THREAD

**Issue by wei053** [generalized-intelligence/GAAS#133]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ y] I am running the latest version of GAAS
- [ y] I checked the Gitbook documentation and found no answer
- [ y] I checked to make sure that this issue has not already been filed
- [ n] I have posted questions regarding Ubuntu, Gazebo, and PX4 in corresponding forums.

# Issue Template

## Context
Please provide any relevant information about your setup.
* Tutorial No.: Tutorial 1/4 
* Mavros:  0.18.4
* ROS: Melodic
* Gazebo: 9
* Ubuntu: 18.04

## Expected Behavior

The drone is flying correctly.
The drone is taking off correctly.

## Current Behavior

rotating while taking off /flying 

move behavior is not working rightly

## Screenshots
https://www.youtube.com/watch?v=MU-yxroWnik&ab_channel=GP
https://www.youtube.com/watch?v=6wHozf-QwZs&ab_channel=GP

**Comment by cyanine-gi** [comment]
I'm sorry but we have ended the support of old gaas version. In our new version the px4 mavros controller is writen in cpp and further documents will be released soon. See our readme.md for more information about new version which is merged from GAAS_contrib.

And for your question, maybe looking into the detailed implementation code of px4_mavros_controller.py is a good idea. There's a parameter for target yaw heading. By default the drone is placed towards east in this map.
