### ISSUE TITLE
Some lapses about the tutorial on the gitbook 

### ISSUE THREAD

**Issue by ElderWanng** [generalized-intelligence/GAAS#14]
## `genromfs` is not a python package
In the section about "environment setting up" of the tutorial part1, when I copy the python modules command, I found that pip can't find 'genromfs'.
And, as far as I know, `genromfs` can be installed from apt. Hence maybe it should be moved out from `pip install xxx\xxx\xxx`. But, what if missing this step, maybe some potential fatal wrong arise?
##  the path of `px4_mavros_run.py` maybe wrong
`cd ~/GAAS/demo/px4_mavros_scripts/1_px4_mavros_offboard_controller` should be replaced by `.......(your path)/GAAS/demo/tutorial_1/1_px4_mavros_offboard_controller`

**Comment by Doodleshr** [comment]
Thanks for figuring that out, genromfs is a required package of other dependencies and you can install it by
`apt install genromfs`.

For the second issue I assumed readers will clone GAAS to ~/home/user-name directory hence I was using ~/GAAS as the default GAAS directory. I have updated this part to (GAAS_PATH) for clearance.

Thanks for your help.

song
