### ISSUE TITLE
No module named pyquaternion

### ISSUE THREAD

**Issue by wzz644534561** [generalized-intelligence/GAAS#18]
When I try to run "python px4_mavros_run.py",there is a error named "No module named ptquaternion".

**Comment by wzz644534561** [comment]
Run "sudo pip2 install pyquaternion" can solve the problem.

**Comment by ninawrong** [comment]
@MasterPa I think this issue is resolved. Can we close it?

**Comment by ninawrong** [comment]
@wzz644534561 Thank you for sharing your problem and the solution with us all! As you have provided the solution, we will close it for now. But the record will remain on GitHub for other people to refer to.
