### ISSUE TITLE
Is there any solution to control multi-uavs with the GAAS

### ISSUE THREAD

**Issue by myname1234** [generalized-intelligence/GAAS#21]
I want to know ,how can i control multi-uavs with the GAAS, i'm new to  python and mavros.

**Comment by MasterPa** [comment]
So what kind of multi-UAVs you mean? Or what do you want to do with multi-UAVs?

**Comment by myname1234** [comment]
> So what kind of multi-UAVs you mean? Or what do you want to do with multi-UAVs?

I mean control multi-UAVs to move toghter on the same time, like formation. I know the px4 Firmware launch has multi_uav_stil.launch，but i can't use the commander.py to control it directly. How do i change the py file.

**Comment by MasterPa** [comment]
GAAS didn't support control multi-UAVs yet, but we will support it in the future(>6 months maybe). You could leave your requirements here:)

**Comment by Doodle1106** [comment]
closed as stale, reopen if needed.
