### ISSUE TITLE
unused args [rcS] for include of [/home/zhao/catkin_ws/Firmware/launch/posix_sitl.launch]

### ISSUE THREAD

**Issue by zhaodeming** [generalized-intelligence/GAAS#23]
[master.log](https://github.com/generalized-intelligence/GAAS/files/3094339/master.log)
[roslaunch-zhao-Alienware-m15-16849.log](https://github.com/generalized-intelligence/GAAS/files/3094341/roslaunch-zhao-Alienware-m15-16849.log)
[roslaunch-zhao-Alienware-m15-22010.log](https://github.com/generalized-intelligence/GAAS/files/3094344/roslaunch-zhao-Alienware-m15-22010.log)
[rosout.log](https://github.com/generalized-intelligence/GAAS/files/3094345/rosout.log)
[rosout-1-stdout.log](https://github.com/generalized-intelligence/GAAS/files/3094346/rosout-1-stdout.log)
![Screenshot from 2019-04-18 20-16-15](https://user-images.githubusercontent.com/26599875/56360340-f1615080-6216-11e9-842b-e3804cc60874.png)

in the terminal, 
`make px4_sitl_default

make px4_sitl_default sitl_gazebo

source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default

export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd):$(pwd)/Tools/sitl_gazebo

echo $ROS_PACKAGE_PATH`

![Screenshot from 2019-04-18 20-19-20](https://user-images.githubusercontent.com/26599875/56360467-4ac97f80-6217-11e9-96c0-46b4dabb9dce.png)

**Comment by Doodle1106** [comment]
you are not using the right version,  we are currently only working with v1.8.0. 
Closing for now, reopen if you have other issues.
