### ISSUE TITLE
Frame_id should be ROS compatible.

### ISSUE THREAD

**Issue by AlexisTM** [generalized-intelligence/GAAS#24]
Hi there,

The frames should be according to [REP 105](https://www.ros.org/reps/rep-0105.html).

* `frame.body` should be `base_link`
* `frame.local_enu` should be:
    * `odom` if the position is drifting but continuous
    * `map` if the position has discrete jumps (more likely if using GPS) but not drifting

https://github.com/generalized-intelligence/GAAS/blob/6619cb926d66a912f3b9c36a04d5b2fe9d2b9d58/demo/tutorial_1/1_px4_mavros_offboard_controller/commander.py#L38-L53

**Comment by Doodle1106** [comment]
thanks, I will give it a look

**Comment by Doodle1106** [comment]
fixed，reopen if needed.
