### ISSUE TITLE
takeoff failed and "python square.py" failed 

### ISSUE THREAD

**Issue by guoxianzhen** [generalized-intelligence/GAAS#28]
# Issue Template

## Context
Please provide any relevant information about your setup.
* Tutorial No.:[Tutorial 3]
* Mavros: [ 0.18.0]
* ROS: [Kinetic]
* Gazebo: [7]
* Ubuntu: [ 16.04]
* System Platform: [86]

## Expected Behavior
The copter takes off and flies in a square way

## Current Behavior

Everytime I use python px4_mavros_run.py, the console gives 
Px4 Controller Initialized!
Vehicle Took Off Failed!
Then I kill the progress and do python px4_mavros_run.py again. The consoles gives 
Px4 Controller Initialized!
Vehicle Took Off!
But the copter does not follow the command. It just fly in a random path.

## Failure Logs
**Console for takeoff**
guo@guo-Lenovo-TianYi-100-14IBD:~$ cd GAAS/demo/tutorial_3
guo@guo-Lenovo-TianYi-100-14IBD:~/GAAS/demo/tutorial_3$ python px4_mavros_run.pyPx4 Controller Initialized!
Vehicle Took Off Failed!
^Cguo@guo-Lenovo-TianYi-100-14IBD:~/GAAS/demo/tutorial_3python px4_mavros_run.pyPx4 Controller Initialized!
Vehicle Took Off!
**Console for slam** 
********* Tracking frame 3484 **********
I0508 20:49:34.949198  1792 TrackerLK.cpp:110] Tracking frame 1
W0508 20:49:34.978073  1792 TrackerLK.cpp:397] Track last frame not enough valid matches: 0, I will abort this frame
W0508 20:49:34.978164  1792 TrackerLK.cpp:219] Pure vision tracking failed! Reseting system!!
I0508 20:49:34.978199  1792 TrackerLK.cpp:504] Tracker is reseted
I0508 20:49:34.978232  1792 TrackerLK.cpp:506] Current pose = 
000.91478 -0.263826 00.305898 00.969283
00.338744 00.913555 -0.225098 002.85873
-0.220068 00.309536 00.925072 006.18012
000000000 000000000 000000000 000000001
I0508 20:49:34.978381  1792 BackendSlidingWindowG2O.cpp:1716] Backend is reset
I0508 20:49:34.981477  1792 BackendSlidingWindowG2O.cpp:1722] backend reset done.
I0508 20:49:34.981520  1792 TrackerLK.cpp:512] Try init stereo
I0508 20:49:34.981535  1792 ORBExtractor.cpp:470] Calling fast single level
I0508 20:49:34.983662  1792 Tracker.cpp:525] Valid feature is not enough! current:0;min valid num:7
I0508 20:49:34.983932  1792 TrackerLK.cpp:517] Stereo init failed.
I0508 20:49:34.984055  1792 TrackerLK.cpp:114] Tracking frame 2
I0508 20:49:34.984088  1792 TrackerLK.cpp:148] Tracking frame 3
I0508 20:49:34.984108  1792 TrackerLK.cpp:153] Tracker position = 0.969283,2.85873,6.18012,
vision pose: 4.26885, 5.37006, -0.495011
EstimatedPose : 4.26885, 5.37006, -0.495011
[ INFO] [1557319774.984965111, 157.616000000]: Heading received: 135.439447
[ INFO] [1557319774.985343938, 157.616000000]: Heading received: 135.437359
I0508 20:49:35.010515  1792 TrackerLK.cpp:98] 

********* Tracking frame 3485 **********
I0508 20:49:35.010596  1792 TrackerLK.cpp:110] Tracking frame 1
^CW0508 20:49:35.081715  1792 TrackerLK.cpp:397] Track last frame not enough valid matches: 0, I will abort this frame
W0508 20:49:35.081845  1792 TrackerLK.cpp:219] Pure vision tracking failed! Reseting system!!
I0508 20:49:35.081892  1792 TrackerLK.cpp:504] Tracker is reseted
I0508 20:49:35.081948  1792 TrackerLK.cpp:506] Current pose = 
000.91478 -0.263826 00.305898 00.969283
00.338744 00.913555 -0.225098 002.85873
-0.220068 00.309536 00.925072 006.18012
000000000 000000000 000000000 000000001
I0508 20:49:35.082149  1792 BackendSlidingWindowG2O.cpp:1716] Backend is reset
I0508 20:49:35.085438  1792 BackendSlidingWindowG2O.cpp:1722] backend reset done.
I0508 20:49:35.085839  1792 TrackerLK.cpp:512] Try init stereo
I0508 20:49:35.085901  1792 ORBExtractor.cpp:470] Calling fast single level
I0508 20:49:35.106935  1792 Tracker.cpp:525] Valid feature is not enough! current:0;min valid num:7
I0508 20:49:35.107000  1792 TrackerLK.cpp:517] Stereo init failed.
I0508 20:49:35.107018  1792 TrackerLK.cpp:114] Tracking frame 2
I0508 20:49:35.107030  1792 TrackerLK.cpp:148] Tracking frame 3
I0508 20:49:35.107041  1792 TrackerLK.cpp:153] Tracker position = 0.969283,2.85873,6.18012,
vision pose: 4.26885, 5.37006, -0.495011
EstimatedPose : 4.26885, 5.37006, -0.495011

**Comment by Doodle1106** [comment]
Thanks for reporting.
1. "But the copter does not follow the command. It just fly in a random path." 
Have you set relative parameters according to the tutorial and did you see "EKF commencing external vision position fusion" from the terminal where you launched slam.launch? If you didn't see it while following the tutorial, it means slam information was not being fused to px4 and you have to set the vision parameter or wait for "EKF commencing external vision position fusion" to appear in the terminal before taking off the drone. 
2. I have modified takeoff_detection function in px4_mavros_run.py. It should work now. Thanks for reporting.

**Comment by MasterPa** [comment]
Close it for now as it is stale. Reopen if needed.
