### ISSUE TITLE
bad results report

### ISSUE THREAD

**Issue by guoxianzhen** [generalized-intelligence/GAAS#30]
# Issue Template

## Context
Please provide any relevant information about your setup.
* Mavros: [0.18.4]
* ROS: [ Kinetic]
* Gazebo: [ 7]
* Ubuntu: [16.04]
* System Platform: [X86]

## Expected Behavior
I hope the copter could perform better according to the command.
## Current Behavior
Takeoff:
Sometimes when the copter takes off, it will fly higher than the expected location and then hovering around the destination. Sometimes, the copter may flies randomly after taking off.
Land:
During the landing process, the copter will keep fly forward. I hope the copter could land just right below or close to the point where it covering.
Flying mission
The copter has not succeeded flying in a square way. The slam will lose when the copter turning 90 degrees and then the copter will fly randomly. 
In addition, according to the test tutorial, I have installed all the dependencies including Pangolin EIgen3 g2o PLC and Opencv.
I just want to ask it there results are normal or if I have missed some steps.
## Screenshots
These are some screenshots of the trajectories when copters takes off.
![2019-05-09 14-34-54屏幕截图](https://user-images.githubusercontent.com/33980909/57513362-a1bb0400-7340-11e9-802a-8cc99b2eb8f0.png)

![takeoff](https://user-images.githubusercontent.com/33980909/57513265-67e9fd80-7340-11e9-8f06-c3442f88756f.png)

![2019-05-09 14-35-28屏幕截图](https://user-images.githubusercontent.com/33980909/57513394-b3041080-7340-11e9-9360-e250fa0c631b.png)
I also simplifies the mission in square.py. I command the copter to fly to the right for 3 meters then turn around for 90 degrees, land finally. This is the results
![gpslamline1](https://user-images.githubusercontent.com/33980909/57513510-02e2d780-7341-11e9-890a-42beee566c3f.png)

## Failure Logs
**part of the console of slam :*********** Tracking frame 2150 **********
I0510 16:05:06.864307 26386 TrackerLK.cpp:110] Tracking frame 1
I0510 16:05:06.879122 26389 BackendSlidingWindowG2O.cpp:133] new good points: 0 in total immature points: 0
I0510 16:05:06.879212 26389 BackendSlidingWindowG2O.cpp:156] Local BA cost time: 9.9e-08
I0510 16:05:06.879249 26389 BackendSlidingWindowG2O.cpp:182] Deleting KF 0
I0510 16:05:06.879266 26389 BackendSlidingWindowG2O.cpp:193] Erase KF in mpKFs
I0510 16:05:06.879516 26389 BackendSlidingWindowG2O.cpp:199] Done
I0510 16:05:06.879671 26389 BackendSlidingWindowG2O.cpp:427] Clean map point done, total bad points 1
I0510 16:05:06.879696 26389 BackendSlidingWindowG2O.cpp:165] Backend KF: 10, map points: 132
I0510 16:05:06.879714 26389 BackendSlidingWindowG2O.cpp:38] Process new KF done.
I0510 16:05:06.902025 26386 Tracker.cpp:1568] Quit iteration in: 10
I0510 16:05:06.904637 26386 Tracker.cpp:1586] Inlier/total=129/129
I0510 16:05:06.904803 26386 Tracker.cpp:1602] Estimated TCW = 
0.0767104 00.983975 00.160963 0014.6661
-0.983889 0.0485575 00.172059 004.61203
00.161486 -0.171568 00.971847 0010.8394
000000000 000000000 000000000 000000001
I0510 16:05:06.932163 26386 ORBExtractor.cpp:470] Calling fast single level
I0510 16:05:06.935111 26386 TrackerLK.cpp:541] Detect new feature cost time: 0.00319594
I0510 16:05:06.938956 26386 TrackerLK.cpp:613] new stereo: 0, new Mono: 0, update immature: 0, total features: 129
I0510 16:05:06.939127 26386 TrackerLK.cpp:618] Create map point cost time: 0.00722153
I0510 16:05:06.939270 26386 Tracker.cpp:506] Insert keyframe done.
I0510 16:05:06.939328 26386 TrackerLK.cpp:235] Insert KF cost time: 0.0074259
I0510 16:05:06.939479 26386 TrackerLK.cpp:114] Tracking frame 2
I0510 16:05:06.939540 26386 TrackerLK.cpp:148] Tracking frame 3
I0510 16:05:06.939602 26386 TrackerLK.cpp:153] Tracker position = 1.68634,-12.7308,-13.6894,
vision pose: -14.9427, -10.4848, -4.37022
EstimatedPose : -14.9427, -10.4848, -4.37022
I0510 16:05:06.941656 26389 BackendSlidingWindowG2O.cpp:36] Process new KF
QObject::~QObject: Timers cannot be stopped from another thread

Console of px4 Firmware
... logging to /home/guo/.ros/log/bcb47986-72f9-11e9-9dbb-b0c0902a3964/roslaunch-guo-Lenovo-TianYi-100-14IBD-25090.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/loader.py:409: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(text)
started roslaunch server http://guo-Lenovo-TianYi-100-14IBD:43109/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.02
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/in/child_frame_id: base_link
 * /mavros/odometry/in/frame_id: odom
 * /mavros/odometry/in/frame_tf/body_frame_orientation: flu
 * /mavros/odometry/in/frame_tf/local_frame: local_origin_ned
 * /mavros/odometry/out/frame_tf/body_frame_orientation: frd
 * /mavros/odometry/out/frame_tf/local_frame: vision_ned
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 6.8
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: map
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: map
 * /mavros/wheel_odometry/tf/send: True
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mavros (mavros/mavros_node)
    sitl (px4/px4)
    vehicle_spawn_guo_Lenovo_TianYi_100_14IBD_25090_5892815240772984067 (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [25100]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to bcb47986-72f9-11e9-9dbb-b0c0902a3964
process[rosout-1]: started with pid [25113]
started core service [/rosout]
process[sitl-2]: started with pid [25139]
node name: sitl
data path: /home/guo/catkin_ws/src/Firmware
commands file: /home/guo/catkin_ws/src/Firmware/posix-configs/SITL/init/ekf2/iris_stereo_gray_no_gps
65 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

process[gazebo-3]: started with pid [25147]
process[gazebo_gui-4]: started with pid [25154]
process[vehicle_spawn_guo_Lenovo_TianYi_100_14IBD_25090_5892815240772984067-5]: started with pid [25159]
process[mavros-6]: started with pid [25160]
INFO  [dataman] Unknown restart, data manager file 'rootfs/fs/microsd/dataman' size is 11405132 bytes
INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..
[ INFO] [1557475256.572810515]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1557475256.577184771]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1557475256.577387877]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1557475256.577844825]: GCS bridge disabled
Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1557475256.615857364]: Plugin 3dr_radio loaded
[ INFO] [1557475256.620982244]: Plugin 3dr_radio initialized
[ INFO] [1557475256.621286055]: Plugin actuator_control loaded
[ INFO] [1557475256.630845175]: Plugin actuator_control initialized
[ INFO] [1557475256.647018084]: Plugin adsb loaded
[ INFO] [1557475256.663212473]: Plugin adsb initialized
[ INFO] [1557475256.663638018]: Plugin altitude loaded
[ INFO] [1557475256.676851706]: Plugin altitude initialized
[ INFO] [1557475256.677311405]: Plugin cam_imu_sync loaded
[ INFO] [1557475256.679476151]: Plugin cam_imu_sync initialized
[ INFO] [1557475256.680219681]: Plugin command loaded
[ INFO] [1557475256.706815624]: Plugin command initialized
[ INFO] [1557475256.707275688]: Plugin companion_process_status loaded
[ INFO] [1557475256.720203229]: Plugin companion_process_status initialized
[ INFO] [1557475256.720739406]: Plugin debug_value loaded
[ INFO] [1557475256.739027085]: Plugin debug_value initialized
[ INFO] [1557475256.739270099]: Plugin distance_sensor blacklisted
[ INFO] [1557475256.739733269]: Plugin fake_gps loaded
Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1557475256.833805376]: Plugin fake_gps initialized
[ INFO] [1557475256.834341910]: Plugin ftp loaded
[ INFO] [1557475256.848533727]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 134.169.243.94
[ INFO] [1557475256.858632841]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1557475256.881393881]: Plugin ftp initialized
[ INFO] [1557475256.881948055]: Plugin global_position loaded
[ INFO] [1557475256.959289448]: Plugin global_position initialized
[ INFO] [1557475256.959735150]: Plugin gps_rtk loaded
[ INFO] [1557475256.968964349]: Plugin gps_rtk initialized
[ INFO] [1557475256.969449983]: Plugin hil loaded
[ INFO] [1557475257.048677681]: Plugin hil initialized
[ INFO] [1557475257.049249155]: Plugin home_position loaded
[ INFO] [1557475257.073797074]: Plugin home_position initialized
[ INFO] [1557475257.074226634]: Plugin imu loaded
[ INFO] [1557475257.097780951]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1557475257.104162232]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 134.169.243.94
[ INFO] [1557475257.124159802]: Plugin imu initialized
[ INFO] [1557475257.124574443]: Plugin local_position loaded
[ INFO] [1557475257.152289912]: Plugin local_position initialized
[ INFO] [1557475257.152615234]: Plugin log_transfer loaded
[ INFO] [1557475257.161496706]: Plugin log_transfer initialized
[ INFO] [1557475257.161867984]: Plugin manual_control loaded
[ INFO] [1557475257.170535638]: Plugin manual_control initialized
[ INFO] [1557475257.170840035]: Plugin mocap_pose_estimate loaded
[ INFO] [1557475257.186189051]: Plugin mocap_pose_estimate initialized
[ INFO] [1557475257.186487362]: Plugin obstacle_distance loaded
[ INFO] [1557475257.194409856]: Plugin obstacle_distance initialized
[ INFO] [1557475257.194710930]: Plugin odom loaded
[ INFO] [1557475257.215927630]: Plugin odom initialized
[ INFO] [1557475257.216400522]: Plugin param loaded
[ INFO] [1557475257.225368862]: Plugin param initialized
[ INFO] [1557475257.225649762]: Plugin px4flow loaded
[ INFO] [1557475257.245123543]: Plugin px4flow initialized
[ INFO] [1557475257.245197482]: Plugin rangefinder blacklisted
[ INFO] [1557475257.245599425]: Plugin rc_io loaded
[ INFO] [1557475257.256995418]: Plugin rc_io initialized
[ INFO] [1557475257.257089490]: Plugin safety_area blacklisted
[ INFO] [1557475257.257450869]: Plugin setpoint_accel loaded
[ INFO] [1557475257.269748749]: Plugin setpoint_accel initialized
[ INFO] [1557475257.270240251]: Plugin setpoint_attitude loaded
[ INFO] [1557475257.308590995]: Plugin setpoint_attitude initialized
[ INFO] [1557475257.309042919]: Plugin setpoint_position loaded
[ INFO] [1557475257.366109524]: Plugin setpoint_position initialized
[ INFO] [1557475257.366496509]: Plugin setpoint_raw loaded
[ INFO] [1557475257.409950216]: Plugin setpoint_raw initialized
[ INFO] [1557475257.410378266]: Plugin setpoint_velocity loaded
SpawnModel script started
[ INFO] [1557475257.438146065]: Plugin setpoint_velocity initialized
[ INFO] [1557475257.440797012]: Plugin sys_status loaded
[ INFO] [1557475257.476992263]: Plugin sys_status initialized
[ INFO] [1557475257.477332819]: Plugin sys_time loaded
[ INFO] [1557475257.492696595]: TM: Timesync mode: MAVLINK
[ INFO] [1557475257.498475491]: Plugin sys_time initialized
[ INFO] [1557475257.498997393]: Plugin trajectory loaded
[ INFO] [1557475257.519031800]: Plugin trajectory initialized
[ INFO] [1557475257.519361876]: Plugin vfr_hud loaded
[ INFO] [1557475257.520987916]: Plugin vfr_hud initialized
[ INFO] [1557475257.521171882]: Plugin vibration blacklisted
[ INFO] [1557475257.521475096]: Plugin vision_pose_estimate loaded
[ INFO] [1557475257.548657594]: Plugin vision_pose_estimate initialized
[ INFO] [1557475257.549493553]: Plugin vision_speed_estimate loaded
[ INFO] [1557475257.570823694]: Plugin vision_speed_estimate initialized
[ INFO] [1557475257.571282457]: Plugin waypoint loaded
[ INFO] [1557475257.589921316]: Plugin waypoint initialized
[ INFO] [1557475257.590107046]: Plugin wheel_odometry blacklisted
[ INFO] [1557475257.590427102]: Plugin wind_estimation loaded
[ INFO] [1557475257.597709665]: Plugin wind_estimation initialized
[ INFO] [1557475257.597930283]: Autostarting mavlink via USB on PX4
[ INFO] [1557475257.598377298]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1557475257.598524693]: Built-in MAVLink package version: 2019.4.4
[ INFO] [1557475257.598651588]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1557475257.598767568]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[INFO] [1557475257.655319, 0.000000]: Loading model XML from file
[INFO] [1557475257.655938, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[ INFO] [1557475257.939922894, 0.026000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1557475257.966327, 0.050000]: Calling service /gazebo/spawn_sdf_model
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/guo/catkin_ws/src/Firmware/Tools/sitl_gazebo/cmake"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/guo/catkin_ws/src/Firmware/Tools/sitl_gazebo/external"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/guo/catkin_ws/src/Firmware/Tools/sitl_gazebo/include"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/guo/catkin_ws/src/Firmware/Tools/sitl_gazebo/models"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/guo/catkin_ws/src/Firmware/Tools/sitl_gazebo/msgs"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/guo/catkin_ws/src/Firmware/Tools/sitl_gazebo/scripts"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/guo/catkin_ws/src/Firmware/Tools/sitl_gazebo/src"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/guo/catkin_ws/src/Firmware/Tools/sitl_gazebo/worlds"
Warning [parser.cc:778] XML Element[child], child of element[sensor] not defined in SDF. Ignoring[child]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
Warning [parser.cc:778] XML Element[parent], child of element[sensor] not defined in SDF. Ignoring[parent]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[INFO] [1557475258.236667, 0.070000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1557475258.277546639, 0.070000000]: Physics dynamic reconfigure ready.
[vehicle_spawn_guo_Lenovo_TianYi_100_14IBD_25090_5892815240772984067-5] process has finished cleanly
log file: /home/guo/.ros/log/bcb47986-72f9-11e9-9dbb-b0c0902a3964/vehicle_spawn_guo_Lenovo_TianYi_100_14IBD_25090_5892815240772984067-5*.log
[ INFO] [1557475258.717826002, 0.070000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1557475258.718126496, 0.070000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1557475258.727596878, 0.070000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1557475258.728058946, 0.070000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[0] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[1] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[2] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[3] no joint control will be performed for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::propeller_joint] not found for channel[4] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_left_joint] not found for channel[5] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_right_joint] not found for channel[6] no joint control for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[7] no joint control will be performed for this channel.
[Msg] Using MAVLink protocol v2.0
[ INFO] [1557475259.062907810, 0.098000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1557475259.163115377, 0.164000000]: Physics dynamic reconfigure ready.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motors, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/0, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/1, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/imu, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/2, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/motor_speed/3, deleting message. This warning is printed only once.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
INFO  [simulator] Got initial simulation data, running sim..
INFO  [pwm_out_sim] MODE_16PWM
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
pxh> INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2019-05-10/08_01_00.ulg
INFO  [mavlink] partner IP: 127.0.0.1
[ INFO] [1557475260.257204303, 1.128000000]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1557475260.378267336, 1.262000000]: IMU: High resolution IMU detected!
INFO  [mavlink] partner IP: 127.0.0.1
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
[ INFO] [1557475261.238106135, 2.064000000]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1557475261.248689658, 2.072000000]: IMU: High resolution IMU detected!
[ INFO] [1557475261.361614057, 2.176000000]: IMU: Attitude quaternion IMU detected!
[ INFO] [1557475262.705694238, 3.064000000]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1557475262.705787152, 3.064000000]: VER: 1.1: Flight software:     010800ff (96443b3cf3e3adae)
[ INFO] [1557475262.705841238, 3.064000000]: VER: 1.1: Middleware software: 010800ff (96443b3cf3e3adae)
[ INFO] [1557475262.705885628, 3.064000000]: VER: 1.1: OS software:         040f00ff (0000000000000000)
[ INFO] [1557475262.705926492, 3.064000000]: VER: 1.1: Board hardware:      00000001
[ INFO] [1557475262.705969890, 3.064000000]: VER: 1.1: VID/PID:             0000:0000
[ INFO] [1557475262.706015072, 3.064000000]: VER: 1.1: UID:                 0000000100000002
[ INFO] [1557475279.586635608, 12.064000000]: HP: requesting home position
[ INFO] [1557475290.977850830, 17.064000000]: WP: mission received
[ INFO] [1557475306.203129558, 22.064000000]: HP: requesting home position
INFO  [ecl/EKF] EKF commencing external vision position fusion
[ WARN] [1557475321.681447912, 26.810000000]: CMD: Unexpected command 246, result 0
[ INFO] [1557475336.404410881, 32.064000000]: HP: requesting home position
WARN  [commander_tests] Failsafe enabled: no RC
[ WARN] [1557475358.762256937, 39.422000000]: CMD: Unexpected command 176, result 1
[ INFO] [1557475358.778073944, 39.426000000]: WP: reached #0
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_no_gps/gazebo/command/motor_speed, deleting message. This warning is printed only once.
[ INFO] [1557475358.839747618, 39.450000000]: WP: reached #0
[ INFO] [1557475359.078308181, 39.530000000]: WP: reached #0

**Comment by ninawrong** [comment]
Thank you for submitting the issue :)
We will get back to you on Monday.

**Comment by Doodle1106** [comment]
Poor performance is related to optimizePoseFaster()， which replaced optimizecurrentposewithoutIMU in tracker.cpp due to seg faults. I am still working on solving this.

**Comment by grreyes2** [comment]
Curious if there have been any updates on this issue, I am encountering the same problem.

**Comment by Doodle1106** [comment]
have you tried replacing optimizePoseFaster with optimizecurrentposewithoutIMU? It usually helps

**Comment by MasterPa** [comment]
Issue closed, re-open if needed.

**Comment by Rindelwald** [comment]
I had the same problem. Anybody help？
