### ISSUE TITLE
make posix_sitl_default gazebo-ERROR:recipe for target 'gazebo' failed

### ISSUE THREAD

**Issue by lihan519** [generalized-intelligence/GAAS#40]
Perform the following two steps,and report errors
**cd Firmware
make posix_sitl_default gazebo**

specific output:
root@zdd-P45VJ:/home/zdd/GAAS/catkin_ws/src/Firmware#` make posix_sitl_default gazebo -j1
[  0%] Built target git_gazebo
[  2%] Built target df_driver_framework
[  3%] Built target mixer_gen
[  3%] Built target uorb_headers
[  4%] Built target git_driverframework
[  4%] Built target mixer_gen_6dof
[  4%] Built target git_ecl
[  4%] Built target git_gps_devices
[  4%] Built target git_mavlink_v2
[  5%] Generating ../../logs
[  8%] Built target work_queue
[  8%] No forceconfigure step for 'sitl_gazebo'
[  8%] Built target logs_symlink
[  8%] Performing configure step for 'sitl_gazebo'
[  8%] Built target tinybson
-- install-prefix: /usr/local
[ 24%] Built target uorb_msgs
[ 25%] Built target ecl_airdata
[ 25%] Built target perf
[ 25%] Built target ecl_attitude_fw
[ 26%] Built target ecl_geo
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   timer
--   chrono
--   date_time
--   atomic
[ 26%] Built target ecl_geo_lookup
[ 27%] Built target mixer
[ 28%] Built target ecl_tecs
[ 28%] Built target ecl_validation
-- Boost version: 1.58.0
[ 29%] Built target rc
[ 29%] Built target generate_topic_listener
[ 30%] Built target px4_layer
[ 31%] Built target parameters
[ 31%] Built target ecl_l1
[ 32%] Built target battery
-- Building klt_feature_tracker without catkin
[ 32%] Built target airspeed
-- Building OpticalFlow with OpenCV
[ 32%] Built target circuit_breaker
[ 34%] Built target controllib
[ 34%] Built target conversion
[ 35%] Built target drivers__device
[ 35%] Built target mathlib
[ 36%] Built target pid
[ 36%] Built target pwm_limit
[ 38%] Built target flight_tasks
[ 39%] Built target terrain_estimation
[ 40%] Built target tunes
[ 40%] Built target version
[ 40%] Built target platforms__common
[ 40%] Built target drivers_board
[ 41%] Built target systemlib
[ 41%] Built target launchdetection
[ 42%] Built target drivers__airspeed
[ 42%] Built target runway_takeoff
-- catkin DISABLED
Gazebo version: 7.0
-- Using C++17 compiler
[ 42%] Built target drivers__led
[ 44%] Built target ecl_EKF
[ 45%] Built target modules__uORB
[ 45%] Built target drivers__ets_airspeed
[ 45%] Built target drivers__ms4525_airspeed
-- Configuring done
[ 45%] Built target drivers__sdp3x_airspeed
[ 46%] Built target drivers__ll40ls
[ 47%] Built target drivers__ms5525_airspeed
[ 47%] Built target drivers__mb12xx
[ 48%] Built target drivers__sf0x
[ 50%] Built target drivers__sf1xx
[ 51%] Built target drivers__tfmini
[ 51%] Built target drivers__teraranger
[ 51%] Built target drivers__srf02
[ 51%] Built target drivers__leddar_one
[ 51%] Built target drivers__ulanding
Scanning dependencies of target drivers__batt_smbus
[ 51%] Built target drivers__vl53lxx
Scanning dependencies of target drivers__camera_trigger
Scanning dependencies of target drivers__gps
[ 51%] Building CXX object src/drivers/batt_smbus/CMakeFiles/drivers__batt_smbus.dir/batt_smbus.cpp.o
[ 51%] Building CXX object src/drivers/camera_trigger/CMakeFiles/drivers__camera_trigger.dir/camera_trigger.cpp.o
[ 51%] Building CXX object src/drivers/gps/CMakeFiles/drivers__gps.dir/gps.cpp.o
[ 51%] Linking CXX static library libdrivers__batt_smbus.a
[ 51%] Building CXX object src/drivers/camera_trigger/CMakeFiles/drivers__camera_trigger.dir/interfaces/src/camera_interface.cpp.o
[ 51%] Built target drivers__batt_smbus
Scanning dependencies of target drivers__pwm_out_sim
[ 51%] Building CXX object src/drivers/gps/CMakeFiles/drivers__gps.dir/devices/src/gps_helper.cpp.o
[ 51%] Building CXX object src/drivers/camera_trigger/CMakeFiles/drivers__camera_trigger.dir/interfaces/src/pwm.cpp.o
[ 51%] Building CXX object src/drivers/pwm_out_sim/CMakeFiles/drivers__pwm_out_sim.dir/PWMSim.cpp.o
[ 51%] Building CXX object src/drivers/camera_trigger/CMakeFiles/drivers__camera_trigger.dir/interfaces/src/seagull_map2.cpp.o
[ 52%] Building CXX object src/drivers/camera_trigger/CMakeFiles/drivers__camera_trigger.dir/interfaces/src/gpio.cpp.o
[ 52%] Linking CXX static library libdrivers__camera_trigger.a
[ 53%] Building CXX object src/drivers/gps/CMakeFiles/drivers__gps.dir/devices/src/mtk.cpp.o
[ 53%] Built target drivers__camera_trigger
[ 53%] Building CXX object src/drivers/gps/CMakeFiles/drivers__gps.dir/devices/src/ashtech.cpp.o
-- Generating done
-- Build files have been written to: /home/zdd/GAAS/catkin_ws/src/Firmware/build/posix_sitl_default/build_gazebo
[ 53%] Performing build step for 'sitl_gazebo'
[ 53%] Building CXX object src/drivers/gps/CMakeFiles/drivers__gps.dir/devices/src/ubx.cpp.o
[ 53%] Linking CXX static library libdrivers__pwm_out_sim.a
make[7]: *** No rule to make target '/home/zdd/GAAS/catkin_ws/src/Firmware/Tools/sitl_gazebo/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'OpticalFlow.pb.cc'。 停止。
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sensor_msgs.dir/all' failed
make[6]: *** [CMakeFiles/sensor_msgs.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make[5]: *** [all] Error 2
platforms/posix/CMakeFiles/sitl_gazebo.dir/build.make:112: recipe for target 'external/Stamp/sitl_gazebo/sitl_gazebo-build' failed
make[4]: *** [external/Stamp/sitl_gazebo/sitl_gazebo-build] Error 2
CMakeFiles/Makefile2:15276: recipe for target 'platforms/posix/CMakeFiles/sitl_gazebo.dir/all' failed
make[3]: *** [platforms/posix/CMakeFiles/sitl_gazebo.dir/all] Error 2
make[3]: *** 正在等待未完成的任务....
[ 53%] Built target drivers__pwm_out_sim
[ 53%] Linking CXX static library libdrivers__gps.a
[ 53%] Built target drivers__gps
CMakeFiles/Makefile2:17990: recipe for target 'platforms/posix/CMakeFiles/gazebo.dir/rule' failed
make[2]: *** [platforms/posix/CMakeFiles/gazebo.dir/rule] Error 2
Makefile:5681: recipe for target 'gazebo' failed
make[1]: *** [gazebo] Error 2
Makefile:148: recipe for target 'posix_sitl_default' failed
make: *** [posix_sitl_default] Error 2

**Comment by Doodle1106** [comment]
'/home/zdd/GAAS/catkin_ws/src/Firmware/Tools/sitl_gazebo/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'OpticalFlow.pb.cc'。

Did you "sudo apt install protobuf-compiler" , as depicted in the 1st tutorial?
