### ISSUE TITLE
SLAM Loop-closure

### ISSUE THREAD

**Issue by MasterPa** [generalized-intelligence/GAAS#5]
Add loop-closure algorithm to eliminate accumulating errors to the existing feature-based vSLAM through means such as Bags of Words(BoW) and PnP.

**Comment by cyanine-gi** [comment]
Implemented in branch scene_retrieve; launch algorithms/scene_retrieving/bin/ros_global_optimization and algorithms/GlobalOptimizationGraph_GTSAM to start a fully optimization with loop-closing. 
We will not support loop-closing in slam algorithm directly in the short term, for this may rely on some certain slam framework too much; Also implement loop-closing for twice may cause inconsistency map in different modules.
