### ISSUE TITLE
ModuleNotFoundError: No module named 'bresenham3d'

### ISSUE THREAD

**Issue by machenxiang** [generalized-intelligence/GAAS#52]
* Tutorial No.:Tutorial 4
* Mavros: 0.18.4
* ROS: Kinetic
* Gazebo: 7
* Ubuntu: 16.04
* System Platform: X86
* python :Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux

When python Navigator.py  it occurs this problem.
Traceback (most recent call last):
  File "Navigator.py", line 24, in <module>
    from path_optimization.path_pruning import PathPruning
  File "/home/mcx/GAAS/software/Navigator/path_optimization/path_pruning.py", line 3, in <module>
    from bresenham3d import Bresenham3D
ModuleNotFoundError: No module named 'bresenham3d'

I have google this problem. But i just find bresenham no bresenham3d. How can i solve this problem? Thanks in advance.

**Comment by metaphox** [comment]
The package `bresenham3d` is just the file `bresenham3d.py` which should be found under `/home/mcx/GAAS/software/Navigator/path_optimization`, the same directory as `path_pruning.py`. Please make sure you have this file in your system.

**Comment by machenxiang** [comment]
> The package `bresenham3d` is just the file `bresenham3d.py` which should be found under `/home/mcx/GAAS/software/Navigator/path_optimization`, the same directory as `path_pruning.py`. Please make sure you have this file in your system.

Thank you
