### ISSUE TITLE
No point cloud in rviz

### ISSUE THREAD

**Issue by ChenChangHaoWS** [generalized-intelligence/GAAS#56]
# Issue Template

## Context
Please provide any relevant information about your setup.
* Tutorial No.:Tutorial 4
* Mavros: 0.32.1
* ROS: Kinetic
* Gazebo: 7
* Ubuntu: 16.04
* System Platform: X86

## Expected Behavior

When doing the
![图片](https://user-images.githubusercontent.com/37094807/64930969-ad2ab880-d867-11e9-985a-0be3371edd96.png)
I should see point cloud in rviz like
![图片](https://user-images.githubusercontent.com/37094807/64930978-be73c500-d867-11e9-84c7-750d3b960fe0.png)

## Current Behavior

I can't see any point cloud in rviz.

## Screenshots
I just do as the tutorials told, everything I can see in my screen:
![图片](https://user-images.githubusercontent.com/37094807/64931102-d3048d00-d868-11e9-961b-9a27a6196062.png)

## Failure Logs

Copy console log and paste it here.
![图片](https://user-images.githubusercontent.com/37094807/64931132-047d5880-d869-11e9-8ee3-0638ef225dda.png)
![图片](https://user-images.githubusercontent.com/37094807/64931137-1101b100-d869-11e9-9b0c-b702804d452e.png)

And the 'path_planning.launch' consloe log:
... logging to /home/ubuntu/.ros/log/dbb5e6f4-d824-11e9-8baa-03af469f68e4/roslaunch-cch-38852.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://cch:33805/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/landing_target/camera/fov_x: 2.0071286398
 * /mavros/landing_target/camera/fov_y: 2.0071286398
 * /mavros/landing_target/image/height: 480
 * /mavros/landing_target/image/width: 640
 * /mavros/landing_target/land_target_type: VISION_FIDUCIAL
 * /mavros/landing_target/listen_lt: False
 * /mavros/landing_target/mav_frame: LOCAL_NED
 * /mavros/landing_target/target_size/x: 0.3
 * /mavros/landing_target/target_size/y: 0.3
 * /mavros/landing_target/tf/child_frame_id: camera_center
 * /mavros/landing_target/tf/frame_id: landing_target
 * /mavros/landing_target/tf/listen: False
 * /mavros/landing_target/tf/rate_limit: 10.0
 * /mavros/landing_target/tf/send: True
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/in/child_frame_id: base_link
 * /mavros/odometry/in/frame_id: odom
 * /mavros/odometry/in/frame_tf/body_frame_orientation: flu
 * /mavros/odometry/in/frame_tf/local_frame: local_origin_ned
 * /mavros/odometry/out/frame_tf/body_frame_orientation: frd
 * /mavros/odometry/out/frame_tf/local_frame: vision_ned
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: map
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: map
 * /mavros/wheel_odometry/tf/send: True
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mavros (mavros/mavros_node)
    sitl (px4/px4)
    vehicle_spawn_cch_38852_6664878163512917421 (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [38862]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to dbb5e6f4-d824-11e9-8baa-03af469f68e4
process[rosout-1]: started with pid [38875]
started core service [/rosout]
process[sitl-2]: started with pid [38900]
node name: sitl
data path: /home/ubuntu/catkin_ws/src/Firmware
commands file: /home/ubuntu/catkin_ws/src/Firmware/posix-configs/SITL/init/ekf2/iris_stereo_gray_gps
117 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [dataman] Unknown restart, data manager file 'rootfs/fs/microsd/dataman' size is 11405132 bytes
INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..
process[gazebo-3]: started with pid [38910]
process[gazebo_gui-4]: started with pid [38917]
process[vehicle_spawn_cch_38852_6664878163512917421-5]: started with pid [38922]
process[mavros-6]: started with pid [38923]
[ INFO] [1568598843.987638918]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1568598843.992672714]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1568598843.992828898]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1568598843.993239774]: GCS bridge disabled
[ INFO] [1568598844.015337274]: Plugin 3dr_radio loaded
[ INFO] [1568598844.018908599]: Plugin 3dr_radio initialized
[ INFO] [1568598844.019022312]: Plugin actuator_control loaded
[ INFO] [1568598844.026518085]: Plugin actuator_control initialized
[ INFO] [1568598844.031140907]: Plugin adsb loaded
[ INFO] [1568598844.039618507]: Plugin adsb initialized
[ INFO] [1568598844.039985321]: Plugin altitude loaded
[ INFO] [1568598844.042644586]: Plugin altitude initialized
Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1568598844.042969253]: Plugin cam_imu_sync loaded
[ INFO] [1568598844.044721509]: Plugin cam_imu_sync initialized
[ INFO] [1568598844.045088915]: Plugin command loaded
Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1568598844.059599101]: Plugin command initialized
[ INFO] [1568598844.059876621]: Plugin companion_process_status loaded
[ INFO] [1568598844.066793883]: Plugin companion_process_status initialized
[ INFO] [1568598844.067099636]: Plugin debug_value loaded
[ INFO] [1568598844.080889271]: Plugin debug_value initialized
[ INFO] [1568598844.080950031]: Plugin distance_sensor blacklisted
[ INFO] [1568598844.081259451]: Plugin fake_gps loaded
[ INFO] [1568598844.119085069]: Plugin fake_gps initialized
[ INFO] [1568598844.119530156]: Plugin ftp loaded
[ INFO] [1568598844.148565741]: Plugin ftp initialized
[ INFO] [1568598844.149137497]: Plugin global_position loaded
[ INFO] [1568598844.151566923]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1568598844.154826278]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.168.40.62
[ INFO] [1568598844.183133103]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1568598844.184356510]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.168.40.62
[ INFO] [1568598844.207772142]: Plugin global_position initialized
[ INFO] [1568598844.208091092]: Plugin gps_rtk loaded
[ INFO] [1568598844.212955344]: Plugin gps_rtk initialized
[ INFO] [1568598844.213323227]: Plugin hil loaded
[ INFO] [1568598844.236319172]: Plugin hil initialized
[ INFO] [1568598844.236586869]: Plugin home_position loaded
[ INFO] [1568598844.242752492]: Plugin home_position initialized
[ INFO] [1568598844.243023142]: Plugin imu loaded
[ INFO] [1568598844.263540135]: Plugin imu initialized
[ INFO] [1568598844.263829848]: Plugin landing_target loaded
[ INFO] [1568598844.296158695]: Plugin landing_target initialized
[ INFO] [1568598844.296498495]: Plugin local_position loaded
[ INFO] [1568598844.313564980]: Plugin local_position initialized
[ INFO] [1568598844.313863763]: Plugin log_transfer loaded
SpawnModel script started
[ INFO] [1568598844.321670167]: Plugin log_transfer initialized
[ INFO] [1568598844.321999950]: Plugin manual_control loaded
[ INFO] [1568598844.329766881]: Plugin manual_control initialized
[ INFO] [1568598844.329988251]: Plugin mocap_pose_estimate loaded
[ INFO] [1568598844.340201765]: Plugin mocap_pose_estimate initialized
[ INFO] [1568598844.340493618]: Plugin mount_control loaded
[ INFO] [1568598844.347058849]: Plugin mount_control initialized
[ INFO] [1568598844.347347191]: Plugin obstacle_distance loaded
[ INFO] [1568598844.353895685]: Plugin obstacle_distance initialized
[ INFO] [1568598844.354161630]: Plugin odom loaded
[ INFO] [1568598844.374092314]: Plugin odom initialized
[ INFO] [1568598844.374580554]: Plugin param loaded
[ INFO] [1568598844.382900548]: Plugin param initialized
[ INFO] [1568598844.383190161]: Plugin px4flow loaded
[ INFO] [1568598844.402777885]: Plugin px4flow initialized
[ INFO] [1568598844.402838539]: Plugin rangefinder blacklisted
[ INFO] [1568598844.403207465]: Plugin rc_io loaded
[ INFO] [1568598844.412939839]: Plugin rc_io initialized
[ INFO] [1568598844.413001212]: Plugin safety_area blacklisted
[ INFO] [1568598844.413331959]: Plugin setpoint_accel loaded
[ INFO] [1568598844.422375606]: Plugin setpoint_accel initialized
[ INFO] [1568598844.422877726]: Plugin setpoint_attitude loaded
[ INFO] [1568598844.451979084]: Plugin setpoint_attitude initialized
[ INFO] [1568598844.452352827]: Plugin setpoint_position loaded
[INFO] [1568598844.468882, 0.000000]: Loading model XML from file
[INFO] [1568598844.469312, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[ INFO] [1568598844.499985112]: Plugin setpoint_position initialized
[ INFO] [1568598844.500362342]: Plugin setpoint_raw loaded
[ INFO] [1568598844.526445304]: Plugin setpoint_raw initialized
[ INFO] [1568598844.526866054]: Plugin setpoint_velocity loaded
[ INFO] [1568598844.543599592]: Plugin setpoint_velocity initialized
[ INFO] [1568598844.544321092]: Plugin sys_status loaded
[ INFO] [1568598844.573699063]: Plugin sys_status initialized
[ INFO] [1568598844.574074923]: Plugin sys_time loaded
[ INFO] [1568598844.589595094]: TM: Timesync mode: MAVLINK
[ INFO] [1568598844.592678894]: Plugin sys_time initialized
[ INFO] [1568598844.592968467]: Plugin trajectory loaded
[ INFO] [1568598844.607917216]: Plugin trajectory initialized
[ INFO] [1568598844.608250794]: Plugin vfr_hud loaded
[ INFO] [1568598844.609871191]: Plugin vfr_hud initialized
[ INFO] [1568598844.609943853]: Plugin vibration blacklisted
[ INFO] [1568598844.610204148]: Plugin vision_pose_estimate loaded
[ INFO] [1568598844.632665475]: Plugin vision_pose_estimate initialized
[ INFO] [1568598844.632955318]: Plugin vision_speed_estimate loaded
[ INFO] [1568598844.644049138]: Plugin vision_speed_estimate initialized
[ INFO] [1568598844.644454285]: Plugin waypoint loaded
[ INFO] [1568598844.656459578]: Plugin waypoint initialized
[ INFO] [1568598844.656550866]: Plugin wheel_odometry blacklisted
[ INFO] [1568598844.656817896]: Plugin wind_estimation loaded
[ INFO] [1568598844.658450833]: Plugin wind_estimation initialized
[ INFO] [1568598844.658546924]: Autostarting mavlink via USB on PX4
[ INFO] [1568598844.658814370]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1568598844.658854758]: Built-in MAVLink package version: 2019.8.8
[ INFO] [1568598844.658900744]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1568598844.658967826]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[INFO] [1568598845.983662, 0.000000]: Calling service /gazebo/spawn_sdf_model
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/ubuntu/catkin_ws/src/Firmware/Tools/sitl_gazebo/cmake"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/ubuntu/catkin_ws/src/Firmware/Tools/sitl_gazebo/external"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/ubuntu/catkin_ws/src/Firmware/Tools/sitl_gazebo/include"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/ubuntu/catkin_ws/src/Firmware/Tools/sitl_gazebo/models"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/ubuntu/catkin_ws/src/Firmware/Tools/sitl_gazebo/msgs"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/ubuntu/catkin_ws/src/Firmware/Tools/sitl_gazebo/scripts"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/ubuntu/catkin_ws/src/Firmware/Tools/sitl_gazebo/src"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/ubuntu/catkin_ws/src/Firmware/Tools/sitl_gazebo/worlds"
[INFO] [1568598846.170464, 996.334000]: Spawn status: SpawnModel: Entity pushed to spawn queue, but spawn service timed out waiting for entity to appear in simulation under the name iris_stereo_gray_gps
Warning [parser.cc:778] XML Element[child], child of element[sensor] not defined in SDF. Ignoring[child]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
Warning [parser.cc:778] XML Element[parent], child of element[sensor] not defined in SDF. Ignoring[parent]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[vehicle_spawn_cch_38852_6664878163512917421-5] process has finished cleanly
log file: /home/ubuntu/.ros/log/dbb5e6f4-d824-11e9-8baa-03af469f68e4/vehicle_spawn_cch_38852_6664878163512917421-5*.log
[ INFO] [1568598846.517169814, 996.334000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1568598846.517419428, 996.334000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1568598846.527286665, 996.334000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1568598846.528149628, 996.334000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[0] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[1] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[2] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[3] no joint control will be performed for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::propeller_joint] not found for channel[4] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_left_joint] not found for channel[5] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_right_joint] not found for channel[6] no joint control for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[7] no joint control will be performed for this channel.
[Msg] Using MAVLink protocol v2.0
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motors, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/0, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/1, deleting message. This warning is printed only once.
[ INFO] [1568598846.670110817, 996.356000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1568598846.672344404, 996.358000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1568598846.826615902, 996.508000000]: Physics dynamic reconfigure ready.
[ INFO] [1568598846.836862449, 996.520000000]: Physics dynamic reconfigure ready.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/2, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/3, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/imu, deleting message. This warning is printed only once.
[Err] [Scene.cc:2927] Light [sun] not found. Use topic ~/factory/light to spawn a new light.
[Err] [Scene.cc:2927] Light [sun] not found. Use topic ~/factory/light to spawn a new light.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
INFO  [simulator] Got initial simulation data, running sim..
INFO  [pwm_out_sim] MODE_16PWM
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
INFO  [logger] logger started (mode=all)
pxh> INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2019-09-16/01_54_07.ulg
[ INFO] [1568598847.846489089, 997.506000000]: udp0: Remote address: 127.0.0.1:14557
INFO  [mavlink] partner IP: 127.0.0.1
[ INFO] [1568598847.956244315, 997.612000000]: IMU: High resolution IMU detected!
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
[ INFO] [1568598848.751345670, 998.408000000]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1568598848.755860119, 998.414000000]: IMU: High resolution IMU detected!
[ INFO] [1568598848.858601527, 998.516000000]: IMU: Attitude quaternion IMU detected!
[ INFO] [1568598849.755799558, 999.412000000]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1568598849.755910592, 999.412000000]: VER: 1.1: Flight software:     010800ff (96443b3cf3e3adae)
[ INFO] [1568598849.755988852, 999.412000000]: VER: 1.1: Middleware software: 010800ff (96443b3cf3e3adae)
[ INFO] [1568598849.756041332, 999.412000000]: VER: 1.1: OS software:         040f00ff (0000000000000000)
[ INFO] [1568598849.756087072, 999.412000000]: VER: 1.1: Board hardware:      00000001
[ INFO] [1568598849.756137488, 999.412000000]: VER: 1.1: VID/PID:             0000:0000
[ INFO] [1568598849.756228992, 999.412000000]: VER: 1.1: UID:                 0000000100000002
[ WARN] [1568598849.761542620, 999.418000000]: CMD: Unexpected command 520, result 0
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
[ INFO] [1568598858.773406476, 1008.408000000]: HP: requesting home position
[ INFO] [1568598863.783141454, 1013.408000000]: WP: mission received
[mavros-6] killing on exit
[gazebo_gui-4] killing on exit
[gazebo-3] killing on exit
[sitl-2] killing on exit

Exiting...
pxh> Shutting down
Restoring terminal
[gazebo-3] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by cyanine-gi** [comment]
You may use rostopic hz /cloud_in to check if there are any msgs publishing.
And you may check your rviz configuration, especially the Global Options-> Fixed Frame.

**Comment by MasterPa** [comment]
Issue closed, re-open if needed.
