### ISSUE TITLE
SfM model combined with SLAM

### ISSUE THREAD

**Issue by MasterPa** [generalized-intelligence/GAAS#6]
Given an SfM model, combine it with SLAM generated the global map.

**Comment by cyanine-gi** [comment]
Here we make a "scene" file from an existing SfM model and retrieve this "scene" to relocate aircraft in realtime for accurate navigation or landing.Users can check branch scene_retrieve, though is not quite mature now.
In algorithms/scene_retrieve we've got a framework, and we are working on the implementation of fixing target with scene retrieving module. So do not implement this feature yourself.
I'll leave this issue open.

**Comment by cyanine-gi** [comment]
Implemented in GAAS_contrib, with lidars. vSLAM is not robust enough.
