### ISSUE TITLE
issue when i try to use slam to build 3d model

### ISSUE THREAD

**Issue by onionysy** [generalized-intelligence/GAAS#63]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes ] I am running the latest version of GAAS
- [yes ] I checked the Gitbook documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes ] I Googled/Binged the error messages generated by Ubuntu, Gazebo, and PX4
- [yes ] I have posted questions regarding Ubuntu, Gazebo, and PX4 in corresponding forums.

# Issue Template

## Context
Please provide any relevant information about your setup.
* Tutorial No.:Tutorial 2
* Mavros: forgot
* ROS: Kinetic
* Gazebo: 7
* Ubuntu: 16.04
* System Platform: X86

## Expected Behavior

In your tutorial, after running rostopic list, there are 2 topics called /gi/simulation/XX/image_raw.
But, I follow your tutorial on gitbook and build from source, when I get into the part2, I can't find anything about the camera and I don't know how to use the slam and SfM simulation.
Then I use the docker way for making sure that I didn't miss any tiny. But, still, when I tap in 'rostopic list', /gi doesn't show up.

Did I forget building the "gi package" or something related?

I see it has been raised months age, and you said you will fixed it. But I still been stuck in this. Can you give me some advices? THX

跟着gitbook的教程走，part1 还好说，part2的时候卡住了，毫无头绪，斗胆来issue提问下。找不到相机数据那个topic，是不是得自己设置相机。还有如何安装，调用slam模块?
这个问题之前看别人也提过，据当时说过一阵会被修复。但我还是在这里出现了同样的问题。能麻烦您帮忙解答下我该如何操作么？
## Current Behavior
ROS TOPIC
`/clock
/diagnostics
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/gazebo_gui/parameter_descriptions
/gazebo_gui/parameter_updates
/mavlink/from
/mavlink/to
/mavros/actuator_control
/mavros/adsb/send
/mavros/adsb/vehicle
/mavros/altitude
/mavros/battery
/mavros/cam_imu_sync/cam_imu_stamp
/mavros/companion_process/status
/mavros/debug_value/debug
/mavros/debug_value/debug_vector
/mavros/debug_value/named_value_float
/mavros/debug_value/named_value_int
/mavros/debug_value/send
/mavros/extended_state
/mavros/fake_gps/mocap/tf
/mavros/global_position/compass_hdg
/mavros/global_position/global
/mavros/global_position/gp_lp_offset
/mavros/global_position/gp_origin
/mavros/global_position/home
/mavros/global_position/local
/mavros/global_position/raw/fix
/mavros/global_position/raw/gps_vel
/mavros/global_position/raw/satellites
/mavros/global_position/rel_alt
/mavros/global_position/set_gp_origin
/mavros/gps_rtk/send_rtcm
/mavros/hil/actuator_controls
/mavros/hil/controls
/mavros/hil/gps
/mavros/hil/imu_ned
/mavros/hil/optical_flow
/mavros/hil/rc_inputs
/mavros/hil/state
/mavros/home_position/home
/mavros/home_position/set
/mavros/imu/data
/mavros/imu/data_raw
/mavros/imu/diff_pressure
/mavros/imu/mag
/mavros/imu/static_pressure
/mavros/imu/temperature_baro
/mavros/imu/temperature_imu
/mavros/landing_target/lt_marker
/mavros/landing_target/pose
/mavros/landing_target/pose_in
/mavros/local_position/accel
/mavros/local_position/odom
/mavros/local_position/pose
/mavros/local_position/pose_cov
/mavros/local_position/velocity_body
/mavros/local_position/velocity_body_cov
/mavros/local_position/velocity_local
/mavros/log_transfer/raw/log_data
/mavros/log_transfer/raw/log_entry
/mavros/manual_control/control
/mavros/manual_control/send
/mavros/mission/reached
/mavros/mission/waypoints
/mavros/mocap/pose
/mavros/mount_control/command
/mavros/obstacle/send
/mavros/odometry/in
/mavros/odometry/out
/mavros/param/param_value
/mavros/px4flow/ground_distance
/mavros/px4flow/raw/optical_flow_rad
/mavros/px4flow/raw/send
/mavros/px4flow/temperature
/mavros/radio_status
/mavros/rc/in
/mavros/rc/out
/mavros/rc/override
/mavros/setpoint_accel/accel
/mavros/setpoint_attitude/cmd_vel
/mavros/setpoint_attitude/thrust
/mavros/setpoint_position/global
/mavros/setpoint_position/local
/mavros/setpoint_raw/attitude
/mavros/setpoint_raw/global
/mavros/setpoint_raw/local
/mavros/setpoint_raw/target_attitude
/mavros/setpoint_raw/target_global
/mavros/setpoint_raw/target_local
/mavros/setpoint_velocity/cmd_vel
/mavros/setpoint_velocity/cmd_vel_unstamped
/mavros/state
/mavros/statustext/recv
/mavros/statustext/send
/mavros/target_actuator_control
/mavros/time_reference
/mavros/timesync_status
/mavros/trajectory/desired
/mavros/trajectory/generated
/mavros/trajectory/path
/mavros/vfr_hud
/mavros/vision_pose/pose
/mavros/vision_pose/pose_cov
/mavros/vision_speed/speed_twist_cov
/mavros/wind_estimation
/rosout
/rosout_agg
/tf
/tf_static
`

## Screenshots

Copy console log and paste it here.

**Comment by onionysy** [comment]
And when I try to use the slam, it can not visualize left camera image in real time. It is only the dark screen./home/comac/图片/2019-10-18 16-29-44屏幕截图.png

**Comment by onionysy** [comment]
when i roslaunch, it raise this
`comac@comac-HP-Z840-Workstation:~/GAAS/software/Obstacle_Map$ roslaunch px4 path_planning.launch
... logging to /home/comac/.ros/log/c85b50a4-f182-11e9-ac30-44334c49fbe0/roslaunch-comac-HP-Z840-Workstation-19074.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://comac-HP-Z840-Workstation:42703/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/landing_target/camera/fov_x: 2.0071286398
 * /mavros/landing_target/camera/fov_y: 2.0071286398
 * /mavros/landing_target/image/height: 480
 * /mavros/landing_target/image/width: 640
 * /mavros/landing_target/land_target_type: VISION_FIDUCIAL
 * /mavros/landing_target/listen_lt: False
 * /mavros/landing_target/mav_frame: LOCAL_NED
 * /mavros/landing_target/target_size/x: 0.3
 * /mavros/landing_target/target_size/y: 0.3
 * /mavros/landing_target/tf/child_frame_id: camera_center
 * /mavros/landing_target/tf/frame_id: landing_target
 * /mavros/landing_target/tf/listen: False
 * /mavros/landing_target/tf/rate_limit: 10.0
 * /mavros/landing_target/tf/send: True
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/in/child_frame_id: base_link
 * /mavros/odometry/in/frame_id: odom
 * /mavros/odometry/in/frame_tf/body_frame_orientation: flu
 * /mavros/odometry/in/frame_tf/local_frame: local_origin_ned
 * /mavros/odometry/out/frame_tf/body_frame_orientation: frd
 * /mavros/odometry/out/frame_tf/local_frame: vision_ned
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: map
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: map
 * /mavros/wheel_odometry/tf/send: True
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mavros (mavros/mavros_node)
    sitl (px4/px4)
    vehicle_spawn_comac_HP_Z840_Workstation_19074_939596101739646439 (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [19084]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c85b50a4-f182-11e9-ac30-44334c49fbe0
process[rosout-1]: started with pid [19097]
started core service [/rosout]
process[sitl-2]: started with pid [19122]
node name: sitl
data path: /home/comac/catkin_ws/src/Firmware
commands file: /home/comac/catkin_ws/src/Firmware/posix-configs/SITL/init/ekf2/iris_stereo_gray_gps
179 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [dataman] Unknown restart, data manager file 'rootfs/fs/microsd/dataman' size is 11405132 bytes
process[gazebo-3]: started with pid [19130]
INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..
process[gazebo_gui-4]: started with pid [19139]
process[vehicle_spawn_comac_HP_Z840_Workstation_19074_939596101739646439-5]: started with pid [19144]
process[mavros-6]: started with pid [19145]
[ INFO] [1571387963.091587193]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1571387963.095335822]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1571387963.095465468]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1571387963.095794926]: GCS bridge disabled
[ INFO] [1571387963.114057256]: Plugin 3dr_radio loaded
[ INFO] [1571387963.117837685]: Plugin 3dr_radio initialized
[ INFO] [1571387963.118103013]: Plugin actuator_control loaded
[ INFO] [1571387963.125185336]: Plugin actuator_control initialized
[ INFO] [1571387963.132415721]: Plugin adsb loaded
[ INFO] [1571387963.137400276]: Plugin adsb initialized
[ INFO] [1571387963.137567364]: Plugin altitude loaded
[ INFO] [1571387963.138952010]: Plugin altitude initialized
[ INFO] [1571387963.139083184]: Plugin cam_imu_sync loaded
[ INFO] [1571387963.139868783]: Plugin cam_imu_sync initialized
[ INFO] [1571387963.140040481]: Plugin command loaded
[ INFO] [1571387963.147091298]: Plugin command initialized
[ INFO] [1571387963.147249700]: Plugin companion_process_status loaded
[ INFO] [1571387963.150609851]: Plugin companion_process_status initialized
[ INFO] [1571387963.150751810]: Plugin debug_value loaded
[ INFO] [1571387963.164370184]: Plugin debug_value initialized
[ INFO] [1571387963.164429320]: Plugin distance_sensor blacklisted
[ INFO] [1571387963.164747450]: Plugin fake_gps loaded
Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1571387963.185341186]: Plugin fake_gps initialized
[ INFO] [1571387963.185590640]: Plugin ftp loaded
[ INFO] [1571387963.195314650]: Plugin ftp initialized
[ INFO] [1571387963.195496593]: Plugin global_position loaded
[ INFO] [1571387963.218239093]: Plugin global_position initialized
[ INFO] [1571387963.218395573]: Plugin gps_rtk loaded
[ INFO] [1571387963.221902057]: Plugin gps_rtk initialized
[ INFO] [1571387963.222089773]: Plugin hil loaded
[ INFO] [1571387963.243618418]: Plugin hil initialized
[ INFO] [1571387963.243807112]: Plugin home_position loaded
[ INFO] [1571387963.249683184]: Plugin home_position initialized
[ INFO] [1571387963.249928354]: Plugin imu loaded
[ INFO] [1571387963.263704902]: Plugin imu initialized
[ INFO] [1571387963.263879095]: Plugin landing_target loaded
[ INFO] [1571387963.280729081]: Plugin landing_target initialized
[ INFO] [1571387963.280994006]: Plugin local_position loaded
[ INFO] [1571387963.294512072]: Plugin local_position initialized
[ INFO] [1571387963.294859941]: Plugin log_transfer loaded
[ INFO] [1571387963.304604736]: Plugin log_transfer initialized
[ INFO] [1571387963.304808938]: Plugin manual_control loaded
[ INFO] [1571387963.305552805]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1571387963.306764187]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1571387963.312897452]: Plugin manual_control initialized
[ INFO] [1571387963.313143695]: Plugin mocap_pose_estimate loaded
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.10.10.115
[ INFO] [1571387963.334504127]: Plugin mocap_pose_estimate initialized
[ INFO] [1571387963.334529092]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1571387963.334730878]: Plugin mount_control loaded
[Msg] Waiting for master.
[ INFO] [1571387963.335540459]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1571387963.339429825]: Plugin mount_control initialized
[ INFO] [1571387963.339754307]: Plugin obstacle_distance loaded
[ INFO] [1571387963.343573143]: Plugin obstacle_distance initialized
[ INFO] [1571387963.343814833]: Plugin odom loaded
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.10.10.115
[ INFO] [1571387963.357569020]: Plugin odom initialized
[ INFO] [1571387963.357950873]: Plugin param loaded
[ INFO] [1571387963.363141051]: Plugin param initialized
[ INFO] [1571387963.363427879]: Plugin px4flow loaded
[ INFO] [1571387963.379834179]: Plugin px4flow initialized
[ INFO] [1571387963.379883085]: Plugin rangefinder blacklisted
[ INFO] [1571387963.380203986]: Plugin rc_io loaded
[ INFO] [1571387963.386745915]: Plugin rc_io initialized
[ INFO] [1571387963.386792012]: Plugin safety_area blacklisted
[ INFO] [1571387963.387032062]: Plugin setpoint_accel loaded
[ INFO] [1571387963.395093724]: Plugin setpoint_accel initialized
[ INFO] [1571387963.395435091]: Plugin setpoint_attitude loaded
[ INFO] [1571387963.417767032]: Plugin setpoint_attitude initialized
[ INFO] [1571387963.417994343]: Plugin setpoint_position loaded
[ INFO] [1571387963.440428421]: Plugin setpoint_position initialized
[ INFO] [1571387963.440665608]: Plugin setpoint_raw loaded
SpawnModel script started
[ INFO] [1571387963.453856927]: Plugin setpoint_raw initialized
[ INFO] [1571387963.454108343]: Plugin setpoint_velocity loaded
[ INFO] [1571387963.462385436]: Plugin setpoint_velocity initialized
[ INFO] [1571387963.462738506]: Plugin sys_status loaded
[ INFO] [1571387963.474775700]: Plugin sys_status initialized
[ INFO] [1571387963.474931246]: Plugin sys_time loaded
[ INFO] [1571387963.481231422]: TM: Timesync mode: MAVLINK
[ INFO] [1571387963.482522564]: Plugin sys_time initialized
[ INFO] [1571387963.482683313]: Plugin trajectory loaded
[ INFO] [1571387963.489281856]: Plugin trajectory initialized
[ INFO] [1571387963.489483080]: Plugin vfr_hud loaded
[ INFO] [1571387963.490288343]: Plugin vfr_hud initialized
[ INFO] [1571387963.490327831]: Plugin vibration blacklisted
[ INFO] [1571387963.490479730]: Plugin vision_pose_estimate loaded
[ INFO] [1571387963.500996114]: Plugin vision_pose_estimate initialized
[ INFO] [1571387963.501192242]: Plugin vision_speed_estimate loaded
[ INFO] [1571387963.506749120]: Plugin vision_speed_estimate initialized
[ INFO] [1571387963.506986196]: Plugin waypoint loaded
[ INFO] [1571387963.513392588]: Plugin waypoint initialized
[ INFO] [1571387963.513439628]: Plugin wheel_odometry blacklisted
[ INFO] [1571387963.513666539]: Plugin wind_estimation loaded
[ INFO] [1571387963.514632392]: Plugin wind_estimation initialized
[ INFO] [1571387963.514700456]: Autostarting mavlink via USB on PX4
[ INFO] [1571387963.514872936]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1571387963.514909094]: Built-in MAVLink package version: 2019.9.9
[ INFO] [1571387963.514961223]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1571387963.514997654]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[INFO] [1571387963.586990, 0.000000]: Loading model XML from file
[INFO] [1571387963.587357, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[INFO] [1571387964.193987, 0.000000]: Calling service /gazebo/spawn_sdf_model
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[Wrn] [ModelDatabase.cc:339] Getting models from[http://gazebosim.org/models/]. This may take a few seconds.
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/cmake"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/external"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/include"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/models"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/msgs"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/scripts"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/src"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/worlds"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/.gazebo/models/house_2"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/.gazebo/models/house_2"
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/.gazebo/models/house_3"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/.gazebo/models/oak_tree"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/.gazebo/models/oak_tree"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/.gazebo/models/apartment"
[INFO] [1571388128.448725, 996.334000]: Spawn status: SpawnModel: Entity pushed to spawn queue, but spawn service timed out waiting for entity to appear in simulation under the name iris_stereo_gray_gps
Warning [parser.cc:778] XML Element[child], child of element[sensor] not defined in SDF. Ignoring[child]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
Warning [parser.cc:778] XML Element[parent], child of element[sensor] not defined in SDF. Ignoring[parent]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[vehicle_spawn_comac_HP_Z840_Workstation_19074_939596101739646439-5] process has finished cleanly
log file: /home/comac/.ros/log/c85b50a4-f182-11e9-ac30-44334c49fbe0/vehicle_spawn_comac_HP_Z840_Workstation_19074_939596101739646439-5*.log
[Err] [Plugin.hh:165] Failed to load plugin libgazebo_ros_multicamera.so: libgazebo_ros_multicamera.so: cannot open shared object file: No such file or directory
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[0] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[1] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[2] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[3] no joint control will be performed for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::propeller_joint] not found for channel[4] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_left_joint] not found for channel[5] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_right_joint] not found for channel[6] no joint control for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[7] no joint control will be performed for this channel.
[Msg] Using MAVLink protocol v2.0
[ INFO] [1571388129.001918062, 996.356000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1571388129.003013744, 996.356000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1571388129.092667520, 996.444000000]: Physics dynamic reconfigure ready.
[ INFO] [1571388129.093004609, 996.444000000]: Physics dynamic reconfigure ready.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motors, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/0, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/1, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/2, deleting message. This warning is printed only once.
[Err] [Scene.cc:2927] Light [sun] not found. Use topic ~/factory/light to spawn a new light.
INFO  [simulator] Got initial simulation data, running sim..
INFO  [pwm_out_sim] MODE_16PWM
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
INFO  [logger] logger started (mode=all)
pxh> INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2019-10-18/08_42_10.ulg
INFO  [mavlink] partner IP: 127.0.0.1
[ INFO] [1571388130.141964259, 997.482000000]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1571388130.288733430, 997.630000000]: IMU: High resolution IMU detected!
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
[ INFO] [1571388131.049769223, 998.388000000]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1571388131.052932373, 998.392000000]: IMU: High resolution IMU detected!
[ INFO] [1571388131.195906029, 998.536000000]: IMU: Attitude quaternion IMU detected!
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/3, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/imu, deleting message. This warning is printed only once.
[ INFO] [1571388132.056172691, 999.394000000]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1571388132.056279553, 999.394000000]: VER: 1.1: Flight software:     010800ff (96443b3cf3e3adae)
[ INFO] [1571388132.056336686, 999.394000000]: VER: 1.1: Middleware software: 010800ff (96443b3cf3e3adae)
[ INFO] [1571388132.056399223, 999.394000000]: VER: 1.1: OS software:         040f00ff (0000000000000000)
[ INFO] [1571388132.056452638, 999.394000000]: VER: 1.1: Board hardware:      00000001
[ INFO] [1571388132.056526471, 999.394000000]: VER: 1.1: VID/PID:             0000:0000
[ INFO] [1571388132.056571226, 999.394000000]: VER: 1.1: UID:                 0000000100000002
[ WARN] [1571388132.104512469, 999.440000000]: CMD: Unexpected command 520, result 0
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
[ INFO] [1571388141.069492081, 1008.390000000]: HP: requesting home position
[ INFO] [1571388146.076236950, 1013.390000000]: WP: mission received
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ERROR] [1571388255.475664445, 1122.634000000]: TM : Time jump detected. Resetting time synchroniser.
ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
[ERROR] [1571388488.856532432, 1355.734000000]: TM : Time jump detected. Resetting time synchroniser.
`

I think the reason maybe this
 `[Err] [Plugin.hh:165] Failed to load plugin libgazebo_ros_multicamera.so: libgazebo_ros_multicamera.so: cannot open shared object file: No such file or directory`
But I don't know how to fix it. Can you help me?

**Comment by Doodle1106** [comment]
Sorry for the late response.

It seems like a misconfiguration of ros-gazebo-pkg, can you try the following command?

`sudo apt install ros-kinetic-gazebo-ros-pkgs`

**Comment by onionysy** [comment]
thx for your guide. I have fix it. thank you.
