### ISSUE TITLE
the Navigator can not work as expection

### ISSUE THREAD

**Issue by onionysy** [generalized-intelligence/GAAS#66]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes] I am running the latest version of GAAS
- [ yes] I checked the Gitbook documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [ yes] I Googled/Binged the error messages generated by Ubuntu, Gazebo, and PX4
- [ yes] I have posted questions regarding Ubuntu, Gazebo, and PX4 in corresponding forums.

# Issue Template

## Context
Please provide any relevant information about your setup.
* Tutorial No.:[eg. Tutorial 4]
* Mavros: [eg. 0.18.4]
* ROS: [eg. Kinetic]
* Gazebo: [eg. 7]
* Ubuntu: [eg. 16.04]
* System Platform: [eg. X86]

I want to use Tutorial 4. 
I can  launch the simulation .
`comac@comac-HP-Z840-Workstation:~$ roslaunch px4 path_planning.launch
... logging to /home/comac/.ros/log/391b6068-f3cc-11e9-94fa-44334c49fbe0/roslaunch-comac-HP-Z840-Workstation-16585.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://comac-HP-Z840-Workstation:37541/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/landing_target/camera/fov_x: 2.0071286398
 * /mavros/landing_target/camera/fov_y: 2.0071286398
 * /mavros/landing_target/image/height: 480
 * /mavros/landing_target/image/width: 640
 * /mavros/landing_target/land_target_type: VISION_FIDUCIAL
 * /mavros/landing_target/listen_lt: False
 * /mavros/landing_target/mav_frame: LOCAL_NED
 * /mavros/landing_target/target_size/x: 0.3
 * /mavros/landing_target/target_size/y: 0.3
 * /mavros/landing_target/tf/child_frame_id: camera_center
 * /mavros/landing_target/tf/frame_id: landing_target
 * /mavros/landing_target/tf/listen: False
 * /mavros/landing_target/tf/rate_limit: 10.0
 * /mavros/landing_target/tf/send: True
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/in/child_frame_id: base_link
 * /mavros/odometry/in/frame_id: odom
 * /mavros/odometry/in/frame_tf/body_frame_orientation: flu
 * /mavros/odometry/in/frame_tf/local_frame: local_origin_ned
 * /mavros/odometry/out/frame_tf/body_frame_orientation: frd
 * /mavros/odometry/out/frame_tf/local_frame: vision_ned
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: map
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: map
 * /mavros/wheel_odometry/tf/send: True
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mavros (mavros/mavros_node)
    sitl (px4/px4)
    vehicle_spawn_comac_HP_Z840_Workstation_16585_5223677942913670248 (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [16595]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 391b6068-f3cc-11e9-94fa-44334c49fbe0
process[rosout-1]: started with pid [16608]
started core service [/rosout]
process[sitl-2]: started with pid [16633]
node name: sitl
data path: /home/comac/catkin_ws/src/Firmware
commands file: /home/comac/catkin_ws/src/Firmware/posix-configs/SITL/init/ekf2/iris_stereo_gray_gps
90 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [dataman] Unknown restart, data manager file 'rootfs/fs/microsd/dataman' size is 11405132 bytes
INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..
process[gazebo-3]: started with pid [16643]
process[gazebo_gui-4]: started with pid [16650]
process[vehicle_spawn_comac_HP_Z840_Workstation_16585_5223677942913670248-5]: started with pid [16655]
process[mavros-6]: started with pid [16656]
[ INFO] [1571639407.818774018]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1571639407.822328429]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1571639407.822491737]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1571639407.822805685]: GCS bridge disabled
[ INFO] [1571639407.838535897]: Plugin 3dr_radio loaded
[ INFO] [1571639407.840995080]: Plugin 3dr_radio initialized
[ INFO] [1571639407.841113680]: Plugin actuator_control loaded
[ INFO] [1571639407.845548394]: Plugin actuator_control initialized
[ INFO] [1571639407.852705016]: Plugin adsb loaded
[ INFO] [1571639407.858340713]: Plugin adsb initialized
[ INFO] [1571639407.858510785]: Plugin altitude loaded
[ INFO] [1571639407.860029159]: Plugin altitude initialized
[ INFO] [1571639407.860168674]: Plugin cam_imu_sync loaded
[ INFO] [1571639407.861072721]: Plugin cam_imu_sync initialized
[ INFO] [1571639407.861215214]: Plugin command loaded
[ INFO] [1571639407.871235800]: Plugin command initialized
[ INFO] [1571639407.871454752]: Plugin companion_process_status loaded
[ INFO] [1571639407.875590494]: Plugin companion_process_status initialized
[ INFO] [1571639407.875803197]: Plugin debug_value loaded
[ INFO] [1571639407.884964536]: Plugin debug_value initialized
[ INFO] [1571639407.885001007]: Plugin distance_sensor blacklisted
Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1571639407.885193390]: Plugin fake_gps loaded
Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1571639407.904513522]: Plugin fake_gps initialized
[ INFO] [1571639407.904726496]: Plugin ftp loaded
[ INFO] [1571639407.914641429]: Plugin ftp initialized
[ INFO] [1571639407.914832339]: Plugin global_position loaded
[ INFO] [1571639407.937659831]: Plugin global_position initialized
[ INFO] [1571639407.937812292]: Plugin gps_rtk loaded
[ INFO] [1571639407.941267197]: Plugin gps_rtk initialized
[ INFO] [1571639407.941449092]: Plugin hil loaded
[ INFO] [1571639407.960477657]: Plugin hil initialized
[ INFO] [1571639407.960659992]: Plugin home_position loaded
[ INFO] [1571639407.965449293]: Plugin home_position initialized
[ INFO] [1571639407.965659388]: Plugin imu loaded
[ INFO] [1571639407.976237416]: Plugin imu initialized
[ INFO] [1571639407.976445833]: Plugin landing_target loaded
[ INFO] [1571639407.998888054]: Plugin landing_target initialized
[ INFO] [1571639407.999152356]: Plugin local_position loaded
[ INFO] [1571639408.018993219]: Plugin local_position initialized
[ INFO] [1571639408.019294430]: Plugin log_transfer loaded
[ INFO] [1571639408.025445328]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1571639408.026673051]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1571639408.030276713]: Plugin log_transfer initialized
[ INFO] [1571639408.030575248]: Plugin manual_control loaded
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.10.10.115
[ INFO] [1571639408.039942268]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1571639408.040110864]: Plugin manual_control initialized
[ INFO] [1571639408.040390351]: Plugin mocap_pose_estimate loaded
[Msg] Waiting for master.
[ INFO] [1571639408.040881656]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.10.10.115
[ INFO] [1571639408.048891814]: Plugin mocap_pose_estimate initialized
[ INFO] [1571639408.049192806]: Plugin mount_control loaded
[ INFO] [1571639408.054499021]: Plugin mount_control initialized
[ INFO] [1571639408.054797368]: Plugin obstacle_distance loaded
[ INFO] [1571639408.058993739]: Plugin obstacle_distance initialized
[ INFO] [1571639408.059318735]: Plugin odom loaded
[ INFO] [1571639408.071236880]: Plugin odom initialized
[ INFO] [1571639408.071583702]: Plugin param loaded
[ INFO] [1571639408.076131603]: Plugin param initialized
[ INFO] [1571639408.076329408]: Plugin px4flow loaded
[ INFO] [1571639408.086563890]: Plugin px4flow initialized
[ INFO] [1571639408.086607924]: Plugin rangefinder blacklisted
[ INFO] [1571639408.086895460]: Plugin rc_io loaded
[ INFO] [1571639408.092323726]: Plugin rc_io initialized
[ INFO] [1571639408.092380378]: Plugin safety_area blacklisted
[ INFO] [1571639408.092724049]: Plugin setpoint_accel loaded
[ INFO] [1571639408.098557603]: Plugin setpoint_accel initialized
[ INFO] [1571639408.098865671]: Plugin setpoint_attitude loaded
[ INFO] [1571639408.115166500]: Plugin setpoint_attitude initialized
[ INFO] [1571639408.115359537]: Plugin setpoint_position loaded
[ INFO] [1571639408.133522413]: Plugin setpoint_position initialized
[ INFO] [1571639408.133713998]: Plugin setpoint_raw loaded
SpawnModel script started
[ INFO] [1571639408.144988068]: Plugin setpoint_raw initialized
[ INFO] [1571639408.145168581]: Plugin setpoint_velocity loaded
[ INFO] [1571639408.152489504]: Plugin setpoint_velocity initialized
[ INFO] [1571639408.152816991]: Plugin sys_status loaded
[ INFO] [1571639408.166168893]: Plugin sys_status initialized
[ INFO] [1571639408.166361671]: Plugin sys_time loaded
[ INFO] [1571639408.172312353]: TM: Timesync mode: MAVLINK
[ INFO] [1571639408.174399766]: Plugin sys_time initialized
[ INFO] [1571639408.174551408]: Plugin trajectory loaded
[INFO] [1571639408.179241, 0.000000]: Loading model XML from file
[INFO] [1571639408.179538, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[ INFO] [1571639408.182687018]: Plugin trajectory initialized
[ INFO] [1571639408.182861568]: Plugin vfr_hud loaded
[ INFO] [1571639408.183668902]: Plugin vfr_hud initialized
[ INFO] [1571639408.183701647]: Plugin vibration blacklisted
[ INFO] [1571639408.183866686]: Plugin vision_pose_estimate loaded
[ INFO] [1571639408.192713954]: Plugin vision_pose_estimate initialized
[ INFO] [1571639408.192887649]: Plugin vision_speed_estimate loaded
[ INFO] [1571639408.198165283]: Plugin vision_speed_estimate initialized
[ INFO] [1571639408.198434609]: Plugin waypoint loaded
[ INFO] [1571639408.204049487]: Plugin waypoint initialized
[ INFO] [1571639408.204095520]: Plugin wheel_odometry blacklisted
[ INFO] [1571639408.204305590]: Plugin wind_estimation loaded
[ INFO] [1571639408.205112637]: Plugin wind_estimation initialized
[ INFO] [1571639408.205173679]: Autostarting mavlink via USB on PX4
[ INFO] [1571639408.205374067]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1571639408.205405313]: Built-in MAVLink package version: 2019.9.9
[ INFO] [1571639408.205465076]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1571639408.205501511]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/cmake"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/external"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/include"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/models"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/msgs"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/scripts"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/src"
[Err] [InsertModelWidget.cc:298] Missing model.config for model "/home/comac/catkin_ws/src/Firmware/Tools/sitl_gazebo/worlds"
[INFO] [1571639409.088642, 0.000000]: Calling service /gazebo/spawn_sdf_model
[ INFO] [1571639409.114461817, 996.356000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1571639409.203569463, 996.442000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
Warning [parser.cc:778] XML Element[child], child of element[sensor] not defined in SDF. Ignoring[child]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
Warning [parser.cc:778] XML Element[parent], child of element[sensor] not defined in SDF. Ignoring[parent]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[INFO] [1571639409.355445, 996.530000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1571639409.394272546, 996.530000000]: Physics dynamic reconfigure ready.
[ INFO] [1571639409.394621874, 996.530000000]: Physics dynamic reconfigure ready.
[ INFO] [1571639409.513896301, 996.530000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1571639409.514294020, 996.530000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1571639409.520561596, 996.530000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1571639409.521804221, 996.530000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[0] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[1] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[2] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[3] no joint control will be performed for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::propeller_joint] not found for channel[4] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_left_joint] not found for channel[5] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_right_joint] not found for channel[6] no joint control for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[7] no joint control will be performed for this channel.
[Msg] Using MAVLink protocol v2.0
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motors, deleting message. This warning is printed only once.
[Err] [Scene.cc:2927] Light [sun] not found. Use topic ~/factory/light to spawn a new light.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[Wrn] [msgs.cc:1655] Conversion of sensor type[multicamera] not suppported.
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'TEXCOORD' is currently not supported
[vehicle_spawn_comac_HP_Z840_Workstation_16585_5223677942913670248-5] process has finished cleanly
log file: /home/comac/.ros/log/391b6068-f3cc-11e9-94fa-44334c49fbe0/vehicle_spawn_comac_HP_Z840_Workstation_16585_5223677942913670248-5*.log
INFO  [simulator] Got initial simulation data, running sim..
INFO  [pwm_out_sim] MODE_16PWM
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
INFO  [logger] logger started (mode=all)
pxh> INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2019-10-21/06_30_10.ulg
INFO  [mavlink] partner IP: 127.0.0.1
[ INFO] [1571639410.818914891, 997.722000000]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1571639410.919163268, 997.822000000]: IMU: High resolution IMU detected!
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
[ INFO] [1571639411.719279004, 998.622000000]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1571639411.721389642, 998.624000000]: IMU: High resolution IMU detected!
[ INFO] [1571639411.820968487, 998.722000000]: IMU: Attitude quaternion IMU detected!
[ INFO] [1571639412.725506698, 999.626000000]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1571639412.725604786, 999.626000000]: VER: 1.1: Flight software:     010800ff (96443b3cf3e3adae)
[ INFO] [1571639412.725672125, 999.626000000]: VER: 1.1: Middleware software: 010800ff (96443b3cf3e3adae)
[ INFO] [1571639412.725751342, 999.626000000]: VER: 1.1: OS software:         040f00ff (0000000000000000)
[ INFO] [1571639412.725809000, 999.626000000]: VER: 1.1: Board hardware:      00000001
[ INFO] [1571639412.725899637, 999.626000000]: VER: 1.1: VID/PID:             0000:0000
[ INFO] [1571639412.725953629, 999.626000000]: VER: 1.1: UID:                 0000000100000002
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/3, deleting message. This warning is printed only once.
[ WARN] [1571639413.028404647, 999.924000000]: CMD: Unexpected command 520, result 0
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/imu, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/0, deleting message. This warning is printed only once.
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
[ INFO] [1571639421.738946134, 1008.622000000]: HP: requesting home position
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/1, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_stereo_gray_gps/motor_speed/2, deleting message. This warning is printed only once.
[ INFO] [1571639426.743437385, 1013.622000000]: WP: mission received
` 
And I can see the point cloud in RVIZ like this.
![图片](https://user-images.githubusercontent.com/55376216/67181797-39547080-f410-11e9-918b-5e6ac41cc5a5.png)
After I launch the Octomap. I can get the /occupied_cells_vis_array  topic.
`comac@comac-HP-Z840-Workstation:~$ roslaunch octomap_server octomap_mapping.launch
... logging to /home/comac/.ros/log/391b6068-f3cc-11e9-94fa-44334c49fbe0/roslaunch-comac-HP-Z840-Workstation-18677.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://comac-HP-Z840-Workstation:44033/

SUMMARY
========

PARAMETERS
 * /octomap_server/frame_id: /map
 * /octomap_server/resolution: 0.1
 * /octomap_server/sensor_model/max_range: 10
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    octomap_server (octomap_server/octomap_server_node)

ROS_MASTER_URI=http://localhost:11311

process[octomap_server-1]: started with pid [18694]

`
![图片](https://user-images.githubusercontent.com/55376216/67182097-f941bd80-f410-11e9-8b9e-ebb5677a9a4b.png)

Hower I can not see the navi_path_plan topic in RVIZ.
And when I run the python Navigator.py.There are something wrong and the plane can not avoid the wall but crash on the wall. I think there are something wrong with it but I can find it, I hope you can help me with that. Thank you!

**Comment by onionysy** [comment]
the navi_path_plan topic showed after i use `python Navigator.py` but it can not find a path and the plane crash on the wall.

**Comment by onionysy** [comment]
I think it must be something wrong with that. If you think there are something unclear, can I have you wechat? THX

**Comment by MasterPa** [comment]
You could join our wechat group by following our intro at the readme. However, we prefer to answer questions at GitHub issue.

**Comment by onionysy** [comment]
> You could join our wechat group by following our intro at the readme. However, we prefer to answer questions at GitHub issue.
thx，I want to solve the problem at GITHUB ,too. Can you give me some advice about my question in running Navigation.py? Thank you very much.
