### ISSUE TITLE
Submitting a pull request

### ISSUE THREAD

**Issue by Arsalan66** [generalized-intelligence/GAAS#71]
* Mavros: [eg. 0.18.4]
* ROS: [eg. Kinetic]
* Gazebo: [eg. 7]
* Ubuntu: [eg. 16.04]
* System Platform: [eg. X86]

I've worked on a target detection algorithm, i want it to be reviewed and tested but i'm confused on pulling a request, can anyone help me?

**Comment by ninawrong** [comment]
Hi Arsalan,

There are a lot of good github tutorials online. Please google "pull request" for more information.
We look forward to reviewing your code in the PR section.

**Comment by Arsalan66** [comment]
Thank you so much for the response, I am not familiar with the flow of GitHub that's why I asked
