### ISSUE TITLE
stable hovering is not possible by modifying the ev_delay parameter

### ISSUE THREAD

**Issue by ChanghaoZou** [generalized-intelligence/GAAS#72]
In the tutorial 3 (Using SLAM In GPS Denied Environment For Position Estimation), the following problem was encountered:

After the drone takes off, it cannot hover at a fixed point. The flight path is similar to the circle centered on the hover point, and the radius of the circle becomes larger. 

In a terminal, type:
rostopic echo /mavros/vision_pose/pose
In the current SLAM position estimation information, x,y,z have values.

The ev_delay parameter is modified according to the official documentation (https://dev.px4.io/v1.9.0/en/ros/external_position_estimation.html). however, stable hovering is not possible by modifying the ev_delay parameter.

How to fix this problem?

**Comment by cyanine-gi** [comment]
We recommend you use px4 1.8.0 currently.
