### ISSUE TITLE
About tutorial 3 slam: Excuse me, how can I get the real value of UAV position and attitude?

### ISSUE THREAD

**Issue by pxfdale** [generalized-intelligence/GAAS#73]
## Context
Please provide any relevant information about your setup.
* Tutorial No.:[eg. Tutorial 3]
* Mavros: [eg. 0.18.4]
* ROS: [eg. Kinetic]
* Gazebo: [eg. 7]
* Ubuntu: [eg. 16.04]
* System Platform: [eg. X86]

## Expected

I want to **verify the accuracy** of SLAM estimotion, so I need to **get the real value** of UAV position and attitude.

Does anyone know how to implement this? 
**Which topic** should I "rostopic echo ..."?

### slam estimated attitude → which topic?

Hope to get your help! 

Sincerely!

**Comment by hddgi** [comment]
Sorry for late response, the topic of slam estimated position is `/mavros/vision_pose/pose`, and the topic of the position after fusion vision pose is `/mavros/local_position/pose`.
