### ISSUE TITLE
tracking with TLD and siamRPN

### ISSUE THREAD

**Issue by lenwen-hub** [generalized-intelligence/GAAS#76]
has anyone trying the object tracking with TLD and SiamRPN？

有人尝试过TLD算法吗，我初步完成了kcf的复现，但是我再尝试TLD算法的时候，出现了错误，运行set_init.py 并绘制矩形框后，并没有返回每帧检测的结果

**Comment by hddgi** [comment]
Sorry for late response，Is there any screenshot of command line output？

**Comment by MasterPa** [comment]
Close the issue, reopen if needed.

**Comment by liangpu597** [comment]
@lenwen-hub  你好，我按照教程跑完了KCF的，我这里出现了一个问题，python set_init.py 然后框选需要跟踪的目标，按S，然后track_and_move.py 然后开启小车移动控件，控制小车移动，无人机是在跟随，但是，先前的那个image里面那个框是不变的，想要的效果是在无人机视角下，一直框选该目标，一直跟着走，请问您那里实现了这个功能了吗？能不能借鉴下？
