### ISSUE TITLE
I can't run demo px4_mavros_run.py

### ISSUE THREAD

**Issue by liangpu597** [generalized-intelligence/GAAS#77]
I follow the step.
and run : python px4_mavros_run.py
it display: 
Px4 Controller Initialized!
Traceback (most recent call last):
  File "px4_mavros_run.py", line 304, in <module>
    con.start()
  File "px4_mavros_run.py", line 72, in start
    self.local_target_pub.publish(self.cur_target_pose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 886, in publish
    raise ROSSerializationException(str(e))
rospy.exceptions.ROSSerializationException: <class 'struct.error'>: 'required argument is not a float' when writing 'header: 
  seq: 1
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
coordinate_frame: 9
type_mask: 1016
position: 
  x: 0
  y: 0
  z: 3.2
velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
acceleration_or_force: 
  x: 0.0
  y: 0.0
  z: 0.0
yaw: None
yaw_rate: 1'

Please tell me how to solve it?

**Comment by hddgi** [comment]
Sorry for late response, I have fix this bug in a recent commit.
