### ISSUE TITLE
offboard_control_tutorial

### ISSUE THREAD

**Issue by haniehes** [generalized-intelligence/GAAS#82]
Hi, I am trying to fly my non-commercial hexacopter with offboard control with a companion computer. I installed the GAAS repository in my ubuntu 16.04, ROS kinetic and tried to follow tutorial 1. I have questions: 
1) Where can I find <px4_python_mavros_mainloop.py> file that you mentioned in this tutorial?
2)  I also read gaas.gitbook.io. Is it enough to learn how to do altitude control of drones? If so, how can I develop it to my drone instead of iris? Did you enter drone physics somewhere in the code?
3) I guess, apart from tutorial, we should set the RC settings in the offboard mode, that you should mention.

**Comment by hddgi** [comment]
1. There is no `px4_python_mavros_mainloop.py` file. It should be `px4_mavros_run.py`. The path of this script is `GAAS/demo/tutorial_1/1_px4_mavros_offboard_controller/`.

2. GAAS uses FLU coordinate system to control drone by default. You can control the altitude through the `move()` function of the class `Commander`. 
```python
from commander import Commander
con = Commander()

# for BODY_OFF_SET_ENU or FLU frame, con.move(x,y,z).
# for LOCAL_ENU frame, con.move(x,y,z,BODY_OFF_SET_ENU=False)
# Control the drone to move 1 meter forward and 2 meter upward.
con.move(1, 0, 2) 
```

3. Thank you for your suggestions, we will update the tutorial as appropriate.
