### ISSUE TITLE
The lab E04 ，I saw rviz have /gi/navi_path_plan  but my rviz can not see the "/gi/navi_path_plan" directory.  So I want to know 1.where is the directory about"gi" 2.How Related between rviz and /gi   THX

### ISSUE THREAD

**Issue by freemagicfan** [generalized-intelligence/GAAS#85]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version of GAAS
- [x] I checked the Gitbook documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I Googled/Binged the error messages generated by Ubuntu, Gazebo, and PX4
- [ ] I have posted questions regarding Ubuntu, Gazebo, and PX4 in corresponding forums.

# Issue Template

## Context
Please provide any relevant information about your setup.
* Tutorial No.:[eg. Tutorial 4]
* Mavros: [eg. 0.18.4]
* ROS: [eg. Kinetic]
* Gazebo: [eg. 7]
* Ubuntu: [eg. 16.04]
* System Platform: [eg. X86]

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

What is the current behavior?

## Failure Logs

Copy console log and paste it here.

**Comment by MasterPa** [comment]
Please use English to ask the question. Thank you!

**Comment by MasterPa** [comment]
And please follow the intro to ask, which could let us help you better.

**Comment by hddgi** [comment]
The "/gi/navi_path_plan" is a ROS topic not a directory, you can see more detail about rostopic at [ROS Wiki](http://wiki.ros.org/ROS/Tutorials). 

RVIZ is a 3d visualization tool for ROS applications. It provides a view of your robot model, capture sensor information from robot sensors, and replay captured data. The "/gi/navi_path_plan" is a ROS topic which publish the "visualization_msgs/Marker" messages, and you can visualize the Marker Display data in rviz.
