### ISSUE TITLE
Point Cloud not show up in Glvz

### ISSUE THREAD

**Issue by nba2kolqw** [generalized-intelligence/GAAS#89]
I am working on the tutorials E04. However point cloud is not showing up. I think it is because ROS is not publishing. And it will abort when I run "sh run.sh" Can someone help me with this issues please? 
![Screenshot from 2020-02-15 15-34-14](https://user-images.githubusercontent.com/60185292/74594877-402f7080-5009-11ea-89a9-d8a24204aa0c.png)
![Screenshot from 2020-02-15 15-13-35](https://user-images.githubusercontent.com/60185292/74594880-458cbb00-5009-11ea-934d-cdc4ffdbbee2.png)
![Screenshot from 2020-02-15 15-14-20](https://user-images.githubusercontent.com/60185292/74594881-47ef1500-5009-11ea-9914-4041147a57ec.png)

**Comment by hddgi** [comment]
`/cloud_in` will be published correctly if `sh run.sh` is run successfully. But `sh run.sh` runs wrong on your computer. Please make sure your repo is up-to-date, and maybe compile it again.

**Comment by MasterPa** [comment]
Close the issue, reopen if needed.
