### ISSUE TITLE
Docker support for EO 4? 

### ISSUE THREAD

**Issue by phildo59** [generalized-intelligence/GAAS#90]
Does the tutorials (E02 - E06) have docker support or is it only the first tutorial that works with docker?

Thanks for the help!

**Comment by MasterPa** [comment]
We have a mirror for v0.7 release, that should support all tutorials.
https://gaas.gitbook.io/guide/handy-tools/v0.7-release-mirror-x86
https://gaas.gitbook.io/guide/handy-tools/gaas-prebuilt-package
