### ISSUE TITLE
Tutorial 4 problem running run.sh from Obstacle_Map

### ISSUE THREAD

**Issue by danydownload** [generalized-intelligence/GAAS#94]
## Context
Please provide any relevant information about your setup.
* Tutorial No.: Tutorial 4
* Mavros: 1.0.0
* ROS: Melodic
* Gazebo: 9
* Ubuntu: 18.04
* System Platform: X64

## Expected Behavior
 ruh.sh should generate the disparity map

## Current Behavior
When i run run.sh i have this error "double free or corruption (out)" and the program aborts.
I found that the problem is in the file "(GAAS_PATH)/software/Obstacle_Map/src/dense_reconstruction.cpp"
when he tries to read K1 from yml file but i don't know how to fix it.

## Screenshots
![Screenshot from 2020-02-27 12-20-40](https://user-images.githubusercontent.com/32312612/75440254-b7df9280-595b-11ea-9cde-fc1f5e08f4c1.png)

## Failure Logs

dani@dani-GL502VT:~/catkin_ws/src/GAAS/software/Obstacle_Map$ sh run.sh 
-------------Brief-----------------
left_img_topic: /gi/simulation/left/image_raw
right_img_topic: /gi/simulation/right/image_raw
calib_file_name: calibration/mynteye2.yml
calib_width: 752
calib_height: 480
out_width: 752
out_height: 480
debug: 0
disparityMax: 20
disparityMin: 2
distanceMax: 10
distanceMin: 0.1
conductStereoRectify: 0
RangeOfDisparity: 16
SizeOfBlockWindow: 7
PreFilterSize: 255
PreFilterCap: 63
SmallerBlockSize: 7
MinDisparity: 7
NumDisparities: 32
TextureThreshold: 255
UniquenessRatio: 115
SpeckleWindowSize: 0
Lambda: 0
SigmaColor: 10
displayImage: 0
-----------------------------------
double free or corruption (out)
Aborted (core dumped)

**Comment by danydownload** [comment]
I think the problem is that ROS is compiled with opencv 3.2 while the camera application wants opencv 3.4.5.
However i found a workaroud. Just setting calibration parameters from code instead of reading from file.
![Screenshot from 2020-03-04 13-06-28](https://user-images.githubusercontent.com/32312612/75878149-7185aa00-5e19-11ea-9939-0a7ed99aaf25.png)

An example:
![Screenshot from 2020-03-04 11-54-39](https://user-images.githubusercontent.com/32312612/75878197-83674d00-5e19-11ea-837f-20bc65de5a06.png)

**Comment by MasterPa** [comment]
Thank you! We are also trying to figure out the problem right now:P
