### ISSUE TITLE
ImportError: No module named ros_kcf.srv

### ISSUE THREAD

**Issue by Lndulge666** [generalized-intelligence/GAAS#98]
* ROS:  Kinetic
* Gazebo: 9
* Ubuntu:  16.04

在Tutorial 6中，运行set_init.py时出现错误：ImportError: No module named ros_kcf.srv，请问该如何解决

**Comment by hddgi** [comment]
Please read our tutorial carefully。 In order to keep the environmental variables lean, you have to manually modify `set_init.py` to add dependencies for ROS Service to the list of environmental variables.

**Comment by Ryan18281613101** [comment]
the error still exists after I modified the file set_init.py,line 8,as sys.path.append('/home/GAAS/demo/tutorial_6/GAAS-Object-Tracking-master/KCF/build/devel/lib/python2.7/dist-packages').If I modified in a wrong way?

**Comment by liangpu597** [comment]
@Ryan18281613101 I change the file path, and it works, you can try again

**Comment by omargazebo** [comment]
@hddgi I did the same steps in the tuto still got the same error: ImportError: No module named ros_kcf.srv . Is there a tutorial that shows more details please ? 
@liangpu597 can you please share the path that you used to make it work.

**Comment by SeanX16** [comment]
> the error still exists after I modified the file set_init.py,line 8,as sys.path.append('/home/GAAS/demo/tutorial_6/GAAS-Object-Tracking-master/KCF/build/devel/lib/python2.7/dist-packages').If I modified in a wrong way?

You got the file path wrong. There is a username between /home and /GAAS. Like this: /home/(username)/GAAS...
